import { colors, radii, spacing } from "../../theme/tokens";

export const chatThreadStyles = {
  chatLayout: {
    flex: 1,
  },
  chatHeader: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    gap: spacing.md,
  },
  cleanHeaderTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  cleanHeaderSpacer: {
    flex: 1,
  },
  cleanNavButton: {
    width: 42,
    height: 42,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFBF6",
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    position: "relative",
  },
  cleanHeaderCopy: {
    flex: 1,
    alignItems: "center",
    gap: 2,
  },
  cleanHeaderEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1.1,
  },
  cleanHeaderTitle: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: "800",
  },
  cleanHeaderSubtitle: {
    color: colors.textSecondary,
    fontSize: 12,
    textAlign: "center",
    maxWidth: 220,
  },
  cleanHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  cleanNavBadge: {
    position: "absolute",
    top: -3,
    right: -2,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: radii.pill,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  cleanNavBadgeText: {
    color: colors.white,
    fontSize: 10,
    fontWeight: "800",
  },
  cleanHeaderStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cleanReopenAction: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: "#FFF8F1",
    borderWidth: 1,
    borderColor: "#F1D7C0",
  },
  cleanReopenActionText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "700",
  },
  cleanHeaderChipRail: {
    gap: spacing.xs,
    paddingRight: spacing.sm,
  },
  cleanHeaderChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 9,
    borderRadius: radii.pill,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  cleanHeaderChipAccent: {
    backgroundColor: "#FFF3E7",
    borderColor: "#FFD6B2",
  },
  cleanHeaderChipText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
    maxWidth: 220,
  },
  cleanHeaderChipTextAccent: {
    color: colors.accent,
  },
  chatHeaderTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  chatHeaderIdentity: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    flex: 1,
  },
  userBadge: {
    width: 46,
    height: 46,
    borderRadius: radii.pill,
    backgroundColor: "rgba(244,123,32,0.18)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  userBadgeText: {
    color: colors.accentSoft,
    fontSize: 18,
    fontWeight: "800",
  },
  chatHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  chatEyebrow: {
    color: colors.accentSoft,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  chatTitle: {
    color: colors.white,
    fontSize: 24,
    fontWeight: "800",
  },
  chatSubtitle: {
    color: "rgba(238,243,247,0.74)",
    fontSize: 13,
  },
  chatHeaderActions: {
    alignItems: "flex-end",
    gap: spacing.sm,
  },
  chatHeaderActionRail: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: radii.pill,
    paddingHorizontal: 6,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  chatHeaderMetaRail: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  chatHeaderMetaChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  chatHeaderMetaText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "700",
    maxWidth: 180,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  iconButtonBadge: {
    position: "absolute",
    top: -3,
    right: -3,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: radii.pill,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  iconButtonBadgeText: {
    color: colors.white,
    fontSize: 10,
    fontWeight: "800",
  },
  chatPanel: {
    flex: 1,
    backgroundColor: "transparent",
    paddingTop: spacing.sm,
    paddingHorizontal: spacing.lg,
    gap: spacing.md,
  },
  chatPanelKeyboardVisible: {
    paddingTop: spacing.xs,
    gap: spacing.sm,
  },
  threadHeaderCard: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: radii.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    borderTopColor: "#F0B98B",
    borderTopWidth: 1.5,
    gap: spacing.sm,
  },
  threadHeaderTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.md,
  },
  threadHeaderCopy: {
    flex: 1,
  },
  threadSpotlightBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  threadSpotlightBadgeAccent: {
    backgroundColor: "#FFF1E4",
    borderColor: "#FFD6B2",
  },
  threadSpotlightBadgeSuccess: {
    backgroundColor: "#EEF9F3",
    borderColor: "#BCE8D0",
  },
  threadSpotlightText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  threadSpotlightTextAccent: {
    color: colors.accent,
  },
  threadSpotlightTextSuccess: {
    color: colors.success,
  },
  threadEyebrow: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  threadTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "800",
    marginTop: 2,
  },
  threadDescription: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  threadContextChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  threadContextChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  threadContextChipAccent: {
    backgroundColor: "#FFF1E4",
    borderColor: "#FFD6B2",
  },
  threadContextChipSuccess: {
    backgroundColor: "#EEF9F3",
    borderColor: "#BCE8D0",
  },
  threadContextChipDanger: {
    backgroundColor: "#FDEEEE",
    borderColor: "#F6CACA",
  },
  threadContextChipText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    maxWidth: 220,
  },
  threadContextChipTextAccent: {
    color: colors.accent,
  },
  threadContextChipTextSuccess: {
    color: colors.success,
  },
  threadContextChipTextDanger: {
    color: colors.danger,
  },
  threadInsightGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  threadInsightCard: {
    width: "48%",
    minWidth: 148,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    padding: spacing.sm,
    borderRadius: radii.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  threadInsightCardAccent: {
    backgroundColor: "#FFF8F1",
    borderColor: "#FFD6B2",
  },
  threadInsightCardSuccess: {
    backgroundColor: "#EEF9F3",
    borderColor: "#BCE8D0",
  },
  threadInsightCardDanger: {
    backgroundColor: "#FDEEEE",
    borderColor: "#F6CACA",
  },
  threadInsightIcon: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  threadInsightIconAccent: {
    backgroundColor: "#FFF1E4",
  },
  threadInsightIconSuccess: {
    backgroundColor: "#DDF5E8",
  },
  threadInsightIconDanger: {
    backgroundColor: "#FCE1E1",
  },
  threadInsightCopy: {
    flex: 1,
    gap: 2,
  },
  threadInsightLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  threadInsightValue: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  threadInsightDetail: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  threadTabs: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  cleanTabShell: {
    borderRadius: 20,
    backgroundColor: "#FFF6EE",
    padding: 6,
    borderWidth: 1,
    borderColor: "#E9D7C4",
    shadowColor: colors.ink900,
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  threadTabsShell: {
    backgroundColor: colors.white,
    borderRadius: radii.md,
    padding: 6,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  threadTab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    backgroundColor: "#FFFDFC",
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: "#E9D9C8",
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
  },
  threadTabActive: {
    backgroundColor: colors.ink800,
    borderColor: colors.ink800,
  },
  threadTabText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "700",
  },
  threadTabTextActive: {
    color: colors.white,
  },
  threadTabBadge: {
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: radii.pill,
    backgroundColor: "#FFF1E4",
    alignItems: "center",
    justifyContent: "center",
  },
  threadTabBadgeActive: {
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  threadTabBadgeText: {
    color: colors.accent,
    fontSize: 10,
    fontWeight: "800",
  },
  threadTabBadgeTextActive: {
    color: colors.white,
  },
  threadMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  threadMetaText: {
    color: colors.textSecondary,
    fontSize: 12,
    flex: 1,
  },
  laudosSection: {
    gap: spacing.sm,
  },
  laudosSectionCopy: {
    flex: 1,
    gap: 2,
  },
  laudosSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  laudosSectionEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  laudosSectionTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  laudosRail: {
    gap: spacing.sm,
    paddingRight: spacing.sm,
  },
  laudoChip: {
    width: 196,
    backgroundColor: colors.white,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    padding: spacing.md,
    gap: spacing.xs,
  },
  laudoChipTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  laudoChipEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  laudoChipEyebrowActive: {
    color: colors.accentSoft,
  },
  laudoChipActive: {
    backgroundColor: colors.ink800,
    borderColor: colors.ink800,
  },
  laudoChipTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  laudoChipTitleActive: {
    color: colors.white,
  },
  laudoChipPreview: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    minHeight: 36,
  },
  laudoChipPreviewActive: {
    color: "rgba(255,255,255,0.82)",
  },
  laudoChipMeta: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "600",
  },
  laudoChipMetaActive: {
    color: "rgba(255,255,255,0.66)",
  },
  laudoChipStatus: {
    alignSelf: "flex-start",
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    marginTop: spacing.xs,
  },
  laudoChipStatusText: {
    fontSize: 11,
    fontWeight: "700",
  },
  activityStrip: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.white,
    padding: spacing.md,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  activityStripIcon: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    backgroundColor: "rgba(244,123,32,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  activityStripCopy: {
    flex: 1,
    gap: 2,
  },
  activityStripTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  activityStripBody: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  activityStripTime: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
  },
  offlineReadBanner: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: "#FFD6B2",
    backgroundColor: "#FFF7EE",
    padding: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  offlineReadBannerIcon: {
    width: 36,
    height: 36,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  offlineReadBannerCopy: {
    flex: 1,
    gap: 2,
  },
  offlineReadBannerTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  offlineReadBannerText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  offlineQueueCard: {
    gap: spacing.sm,
    backgroundColor: "#FFF8F1",
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: "#FFD6B2",
    padding: spacing.md,
  },
  offlineQueueHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  offlineQueueActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  offlineQueueCopy: {
    flex: 1,
    gap: 2,
  },
  offlineQueueTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  offlineQueueDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  offlineQueueSummaryChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  offlineQueueSummaryChip: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radii.pill,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  offlineQueueSummaryChipAccent: {
    backgroundColor: "#FFF1E4",
    borderColor: "#FFD6B2",
  },
  offlineQueueSummaryChipDanger: {
    backgroundColor: "#FDEAEA",
    borderColor: "#F6CACA",
  },
  offlineQueueSummaryChipText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  offlineQueueSummaryChipTextAccent: {
    color: colors.accent,
  },
  offlineQueueSummaryChipTextDanger: {
    color: colors.danger,
  },
  offlineQueueSyncButton: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#FFD6B2",
  },
  offlineQueueOpenButton: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#FFD6B2",
  },
  offlineQueueSyncButtonDisabled: {
    opacity: 0.55,
  },
  offlineQueueItems: {
    gap: spacing.xs,
  },
  offlineQueueItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    backgroundColor: colors.white,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: "#FFE7CF",
    paddingHorizontal: spacing.sm,
    paddingVertical: 10,
  },
  offlineQueueItemContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  offlineQueueItemBadge: {
    width: 32,
    height: 32,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF1E4",
  },
  offlineQueueItemCopy: {
    flex: 1,
    gap: 2,
  },
  offlineQueueItemTitle: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
  },
  offlineQueueItemText: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  offlineQueueItemMeta: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  offlineQueueItemRemove: {
    width: 28,
    height: 28,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  offlineQueueFooter: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  offlineModalToolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: radii.md,
    backgroundColor: "#FFF8F1",
    borderWidth: 1,
    borderColor: "#FFE2C4",
  },
  offlineModalToolbarText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  offlineModalSyncButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#FFD6B2",
  },
  offlineModalSyncButtonDisabled: {
    opacity: 0.55,
  },
  offlineModalSyncText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "700",
  },
  offlineModalSyncTextDisabled: {
    color: colors.textSecondary,
  },
  offlineModalFilters: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  offlineModalFilterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  offlineModalFilterChipActive: {
    backgroundColor: "#FFF1E4",
    borderColor: "#FFD6B2",
  },
  offlineModalFilterText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  offlineModalFilterTextActive: {
    color: colors.accent,
  },
  offlineModalFilterCount: {
    minWidth: 24,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  offlineModalFilterCountActive: {
    backgroundColor: colors.accent,
  },
  offlineModalFilterCountText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  offlineModalFilterCountTextActive: {
    color: colors.white,
  },
  offlineModalItem: {
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: radii.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  offlineModalItemTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  offlineModalItemBadge: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF1E4",
  },
  offlineModalItemCopy: {
    flex: 1,
    gap: 4,
  },
  offlineModalItemHeading: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  offlineModalItemTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  offlineModalItemTime: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  offlineModalItemText: {
    color: colors.textPrimary,
    fontSize: 13,
    lineHeight: 19,
  },
  offlineModalItemHint: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  offlineModalItemStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    flexWrap: "wrap",
  },
  offlineModalItemStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radii.pill,
    backgroundColor: "#FFF1E4",
  },
  offlineModalItemStatusBadgeError: {
    backgroundColor: "#FDEAEA",
  },
  offlineModalItemStatusBadgeText: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
  },
  offlineModalItemStatusBadgeTextError: {
    color: colors.danger,
  },
  offlineModalItemStatusText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  offlineModalItemActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: spacing.xs,
    flexWrap: "wrap",
  },
  offlineModalActionGhost: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radii.pill,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#FFD6B2",
  },
  offlineModalActionGhostDisabled: {
    opacity: 0.55,
  },
  offlineModalActionGhostText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "700",
  },
  offlineModalActionGhostTextDisabled: {
    color: colors.textSecondary,
  },
  offlineModalActionPrimary: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radii.pill,
    backgroundColor: colors.accent,
  },
  offlineModalActionPrimaryText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "800",
  },
  offlineModalActionSecondary: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceSoft,
  },
  offlineModalActionSecondaryText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  laudoStatusBadge: {
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
  },
  laudoStatusText: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  reopenButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: "#FFF5ED",
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
  },
  reopenButtonText: {
    color: colors.accent,
    fontWeight: "700",
  },
  threadBody: {
    flex: 1,
    minHeight: 280,
    backgroundColor: "#FFFCF7",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#EADAC8",
    borderTopColor: "#F0B98B",
    borderTopWidth: 1.5,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    shadowColor: colors.ink900,
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  threadBodyKeyboardVisible: {
    minHeight: 220,
  },
  threadEmptyState: {
    minHeight: 260,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.xl,
  },
  threadEmptyBrandStage: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.md,
  },
  threadEmptyBrandHalo: {
    position: "absolute",
    top: -12,
    width: 122,
    height: 122,
    borderRadius: 61,
    backgroundColor: "rgba(244,123,32,0.08)",
  },
  threadEmptyBrandMark: {
    width: 88,
    height: 88,
    borderRadius: 28,
    shadowColor: colors.ink900,
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  threadEmptyBrand: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1.4,
    marginTop: -2,
  },
  threadEmptyTitle: {
    color: colors.textPrimary,
    fontSize: 23,
    fontWeight: "800",
    textAlign: "center",
    lineHeight: 31,
    maxWidth: 300,
  },
  threadEmptyText: {
    color: colors.textSecondary,
    fontSize: 15,
    lineHeight: 23,
    textAlign: "center",
    maxWidth: 300,
  },
  threadEmptySuggestionRail: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  threadEmptySuggestion: {
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: "#FFD9BC",
    backgroundColor: "#FFF8F1",
  },
  threadEmptySuggestionText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "700",
  },
  threadContent: {
    paddingTop: spacing.xs,
    paddingBottom: spacing.md,
    gap: spacing.md,
  },
  threadContentKeyboard: {
    paddingBottom: spacing.lg,
  },
  messageRow: {
    width: "100%",
  },
  messageRowIncoming: {
    alignItems: "flex-start",
  },
  messageRowOutgoing: {
    alignItems: "flex-end",
  },
  messageIncomingCluster: {
    maxWidth: "92%",
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 10,
  },
  messageAvatar: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    marginBottom: 6,
  },
  messageAvatarTariel: {
    backgroundColor: "#EEF5FB",
    borderColor: "#D9E6F2",
  },
  messageAvatarBrand: {
    width: 36,
    height: 36,
    borderRadius: 12,
    marginBottom: 6,
    shadowColor: colors.ink900,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  messageAvatarEngineering: {
    backgroundColor: "#FFF4E8",
    borderColor: "#EEC8A7",
  },
  messageAvatarMesa: {
    backgroundColor: "#FFF4E8",
    borderColor: "#EEC8A7",
  },
  messageBubble: {
    maxWidth: "84%",
    borderRadius: 24,
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    gap: 8,
  },
  messageBubbleIncomingShell: {
    flexShrink: 1,
    maxWidth: "100%",
  },
  messageBubbleIncoming: {
    backgroundColor: "#FFF9F3",
    borderWidth: 1,
    borderColor: "#EEDFD0",
    borderTopWidth: 1.5,
    borderTopColor: "#F5CAA0",
    borderTopLeftRadius: 18,
    borderBottomLeftRadius: 10,
    shadowColor: colors.ink900,
    shadowOpacity: 0.035,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 2,
  },
  messageBubbleOutgoing: {
    backgroundColor: "#182536",
    borderWidth: 1,
    borderColor: "#2B3950",
    borderTopWidth: 1.5,
    borderTopColor: "rgba(255,180,120,0.6)",
    borderTopRightRadius: 18,
    borderBottomRightRadius: 10,
    shadowColor: colors.ink900,
    shadowOpacity: 0.1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  messageBubbleEngineering: {
    backgroundColor: "#FFF2E6",
    borderWidth: 1,
    borderColor: "#F0C9A4",
    borderLeftWidth: 3,
    borderLeftColor: "#F3B67A",
    borderTopLeftRadius: 18,
    borderBottomLeftRadius: 10,
    shadowColor: colors.ink900,
    shadowOpacity: 0.03,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 2,
  },
  messageBubbleReferenced: {
    borderColor: "#F6C190",
    borderWidth: 1.5,
  },
  messageAuthor: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  messageAuthorOutgoing: {
    color: colors.accentSoft,
  },
  messageHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  messageStatusBadge: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: radii.pill,
    borderWidth: 1,
  },
  messageStatusBadgeAccent: {
    backgroundColor: "#FFF1E4",
    borderColor: "#FFD6B2",
  },
  messageStatusBadgeSuccess: {
    backgroundColor: "#EEF9F3",
    borderColor: "#BCE8D0",
  },
  messageStatusBadgeText: {
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  messageStatusBadgeTextAccent: {
    color: colors.accent,
  },
  messageStatusBadgeTextSuccess: {
    color: colors.success,
  },
  messageText: {
    color: colors.textPrimary,
    fontSize: 15,
    lineHeight: 24,
  },
  messageTextOutgoing: {
    color: colors.white,
  },
  messageMeta: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  messageMetaOutgoing: {
    color: "rgba(255,255,255,0.74)",
    alignSelf: "flex-end",
  },
  messageReferenceCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E8D7C6",
    backgroundColor: "#FFF8F1",
    paddingHorizontal: spacing.sm,
    paddingVertical: 10,
  },
  messageReferenceCardOutgoing: {
    borderColor: "rgba(255,255,255,0.24)",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  messageReferenceIcon: {
    width: 24,
    height: 24,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFE9D4",
  },
  messageReferenceIconOutgoing: {
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  messageReferenceCopy: {
    flex: 1,
    gap: 2,
  },
  messageReferenceTitle: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  messageReferenceTitleOutgoing: {
    color: "rgba(255,255,255,0.86)",
  },
  messageReferenceText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  messageReferenceTextOutgoing: {
    color: "rgba(255,255,255,0.8)",
  },
  messageActionRow: {
    paddingTop: 2,
  },
  messageActionButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: "#EEC8A7",
    backgroundColor: "#FFF2E5",
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
  },
  messageActionText: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "700",
  },
  messageAttachments: {
    gap: spacing.xs,
  },
  messageAttachmentCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: "#FFF7EF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EEDCC9",
    padding: spacing.sm,
  },
  messageAttachmentCardDisabled: {
    opacity: 0.7,
  },
  messageAttachmentIconCircle: {
    width: 38,
    height: 38,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFE8D2",
  },
  messageAttachmentImagePreview: {
    width: 52,
    height: 52,
    borderRadius: radii.sm,
    backgroundColor: "#E8EDF2",
  },
  messageAttachmentBody: {
    flex: 1,
    gap: 2,
  },
  messageAttachmentTitle: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "600",
  },
  messageAttachmentCaption: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  messageAttachmentAction: {
    width: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  typingRow: {
    alignItems: "flex-start",
  },
  typingBubble: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: "#FFFBF7",
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#E8D8C9",
  },
  typingText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "600",
  },
  composerCard: {
    backgroundColor: "#FFFCF8",
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "#EAD9C8",
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.lg,
    gap: spacing.sm,
    shadowColor: colors.ink900,
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  composerCardKeyboardVisible: {
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
    gap: spacing.xs,
  },
  composerHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  composerHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  composerEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  composerTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  composerSubtitle: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  composerStatusBadge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  composerStatusBadgeAccent: {
    backgroundColor: "#FFF2E5",
    borderColor: "#EEC8A7",
  },
  composerStatusBadgeSuccess: {
    backgroundColor: "#EEF9F3",
    borderColor: "#BCE8D0",
  },
  composerStatusBadgeText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  composerStatusBadgeTextAccent: {
    color: colors.accent,
  },
  composerStatusBadgeTextSuccess: {
    color: colors.success,
  },
  composerHint: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    paddingHorizontal: 2,
  },
  composerToolsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    flexWrap: "wrap",
  },
  composerToolsLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  composerToolsText: {
    color: colors.textSecondary,
    fontSize: 12,
    flex: 1,
    textAlign: "left",
    minWidth: 180,
  },
  attachButton: {
    width: 42,
    height: 42,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  attachButtonDisabled: {
    opacity: 0.45,
  },
  attachmentDraftCard: {
    backgroundColor: "#FFFCF8",
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: "#E8D8C9",
    padding: spacing.md,
  },
  attachmentDraftHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  attachmentDraftIcon: {
    width: 36,
    height: 36,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFEEDF",
  },
  attachmentDraftPreview: {
    width: 52,
    height: 52,
    borderRadius: radii.sm,
    backgroundColor: "#E8EDF2",
  },
  attachmentDraftCopy: {
    flex: 1,
    gap: 2,
  },
  attachmentDraftTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  attachmentDraftDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  attachmentDraftRemove: {
    width: 30,
    height: 30,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  composerReferenceCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: "#E7D8C8",
    backgroundColor: "#FFF8F1",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  composerReferenceCopy: {
    flex: 1,
    gap: 2,
  },
  composerReferenceTitle: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  composerReferenceText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  composerReferenceRemove: {
    width: 28,
    height: 28,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
} as const;
