import {
  colors,
  radii,
  shadows,
  spacing,
  typography,
} from "../../theme/tokens";

export const chatThreadStyles = {
  chatLayout: {
    flex: 1,
    minHeight: 0,
  },
  chatHeader: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
    gap: spacing.xs,
  },
  chatHeaderCompact: {
    paddingBottom: 2,
    gap: 6,
  },
  cleanHeaderTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  cleanHeaderSpacer: {
    flex: 1,
  },
  cleanNavButton: {
    width: 46,
    height: 46,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    position: "relative",
    ...shadows.soft,
  },
  cleanNavButtonCompact: {
    width: 42,
    height: 42,
  },
  cleanHeaderCopy: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 1,
    minHeight: 46,
  },
  cleanHeaderCopyCompact: {
    minHeight: 42,
  },
  chatHomeButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    minHeight: 32,
  },
  chatHomeButtonCompact: {
    gap: 6,
    minHeight: 28,
  },
  chatHomeIcon: {
    width: 22,
    height: 22,
    borderRadius: 7,
  },
  chatHomeIconCompact: {
    width: 20,
    height: 20,
    borderRadius: 6,
  },
  cleanHeaderEyebrow: {
    color: colors.textMuted,
    ...typography.eyebrow,
  },
  cleanHeaderTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
  },
  cleanHeaderTitleCompact: {
    fontSize: 18,
    lineHeight: 22,
  },
  cleanHeaderSubtitle: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 15,
    textAlign: "center",
    maxWidth: 240,
  },
  cleanHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  cleanNavBadge: {
    position: "absolute",
    top: -3,
    right: -2,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: radii.pill,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  cleanNavBadgeText: {
    color: colors.white,
    fontSize: 10,
    fontWeight: "800",
  },
  cleanHeaderStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 0,
  },
  cleanReopenAction: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  cleanReopenActionText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
  },
  composerMiniActions: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 2,
  },
  composerMiniAction: {
    width: 26,
    height: 26,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  cleanHeaderChipRail: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 6,
  },
  cleanHeaderChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radii.pill,
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
  },
  cleanHeaderChipAccent: {
    backgroundColor: colors.accentWash,
    borderColor: colors.accentMuted,
  },
  cleanHeaderChipText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
    maxWidth: 220,
  },
  cleanHeaderChipTextAccent: {
    color: colors.accent,
  },
  chatHeaderTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  chatHeaderIdentity: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    flex: 1,
  },
  userBadge: {
    width: 46,
    height: 46,
    borderRadius: radii.pill,
    backgroundColor: "rgba(244,123,32,0.18)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  userBadgeText: {
    color: colors.accentSoft,
    fontSize: 18,
    fontWeight: "800",
  },
  chatHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  chatEyebrow: {
    color: colors.accentSoft,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  chatTitle: {
    color: colors.white,
    fontSize: 24,
    fontWeight: "800",
  },
  chatSubtitle: {
    color: "rgba(238,243,247,0.74)",
    fontSize: 13,
  },
  chatHeaderActions: {
    alignItems: "flex-end",
    gap: spacing.sm,
  },
  chatHeaderActionRail: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: radii.pill,
    paddingHorizontal: 6,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  chatHeaderMetaRail: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  chatHeaderMetaChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  chatHeaderMetaText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "700",
    maxWidth: 180,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  iconButtonBadge: {
    position: "absolute",
    top: -3,
    right: -3,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: radii.pill,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  iconButtonBadgeText: {
    color: colors.white,
    fontSize: 10,
    fontWeight: "800",
  },
  chatPanel: {
    flex: 1,
    minHeight: 0,
    backgroundColor: "transparent",
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    paddingHorizontal: spacing.lg,
    gap: spacing.md,
  },
  chatPanelKeyboardVisible: {
    paddingTop: 0,
    paddingBottom: spacing.xs,
    gap: spacing.sm,
  },
  threadHeaderCard: {
    backgroundColor: colors.surfacePanelRaised,
    borderRadius: 26,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    gap: spacing.md,
    ...shadows.soft,
  },
  threadHeaderTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.md,
  },
  threadHeaderCopy: {
    flex: 1,
  },
  threadSpotlightBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
  },
  threadSpotlightBadgeAccent: {
    backgroundColor: colors.accentWash,
    borderColor: colors.accentMuted,
  },
  threadSpotlightBadgeSuccess: {
    backgroundColor: colors.successWash,
    borderColor: colors.successSoft,
  },
  threadSpotlightText: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  threadSpotlightTextAccent: {
    color: colors.accent,
  },
  threadSpotlightTextSuccess: {
    color: colors.success,
  },
  threadEyebrow: {
    color: colors.textMuted,
    ...typography.eyebrow,
  },
  threadTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
    marginTop: 2,
  },
  threadDescription: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  threadContextChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  threadContextChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceCanvas,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
  },
  threadContextChipAccent: {
    backgroundColor: colors.accentWash,
    borderColor: colors.accentMuted,
  },
  threadContextChipSuccess: {
    backgroundColor: colors.successWash,
    borderColor: colors.successSoft,
  },
  threadContextChipDanger: {
    backgroundColor: colors.dangerWash,
    borderColor: colors.dangerSoft,
  },
  threadContextChipText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    maxWidth: 220,
  },
  threadContextChipTextAccent: {
    color: colors.accent,
  },
  threadContextChipTextSuccess: {
    color: colors.success,
  },
  threadContextChipTextDanger: {
    color: colors.danger,
  },
  threadInsightGrid: {
    flexDirection: "column",
    gap: spacing.sm,
  },
  threadInsightCard: {
    width: "100%",
    minWidth: 0,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: 20,
    backgroundColor: colors.surfacePanel,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    ...shadows.soft,
  },
  threadInsightCardAccent: {
    backgroundColor: colors.accentWash,
    borderColor: colors.accentMuted,
  },
  threadInsightCardSuccess: {
    backgroundColor: colors.successWash,
    borderColor: colors.successSoft,
  },
  threadInsightCardDanger: {
    backgroundColor: colors.dangerWash,
    borderColor: colors.dangerSoft,
  },
  threadInsightIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfacePanelRaised,
  },
  threadInsightIconAccent: {
    backgroundColor: colors.accentMuted,
  },
  threadInsightIconSuccess: {
    backgroundColor: "#DDF5E8",
  },
  threadInsightIconDanger: {
    backgroundColor: "#FCE1E1",
  },
  threadInsightCopy: {
    flex: 1,
    gap: 2,
  },
  threadInsightLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  threadInsightValue: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  threadInsightDetail: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  threadTabs: {
    flexDirection: "row",
    gap: spacing.xs,
  },
  threadTabsCompact: {
    gap: 6,
  },
  cleanTabShell: {
    borderRadius: 20,
    backgroundColor: colors.surfacePanelRaised,
    padding: 4,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    ...shadows.soft,
  },
  cleanTabShellCompact: {
    padding: 3,
  },
  threadTabsShell: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.md,
    padding: 6,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
  },
  threadTab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    backgroundColor: "transparent",
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
  },
  threadTabCompact: {
    paddingVertical: 8,
    paddingHorizontal: spacing.sm,
  },
  threadTabActive: {
    backgroundColor: colors.ink800,
    borderColor: colors.ink800,
    ...shadows.soft,
  },
  threadTabText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: "700",
  },
  threadTabTextCompact: {
    fontSize: 13,
  },
  threadTabTextActive: {
    color: colors.white,
  },
  threadTabBadge: {
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: radii.pill,
    backgroundColor: colors.accentWash,
    alignItems: "center",
    justifyContent: "center",
  },
  threadTabBadgeActive: {
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  threadTabBadgeText: {
    color: colors.accent,
    fontSize: 10,
    fontWeight: "800",
  },
  threadTabBadgeTextActive: {
    color: colors.white,
  },
  threadMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  threadMetaText: {
    color: colors.textSecondary,
    fontSize: 12,
    flex: 1,
  },
  laudosSection: {
    gap: spacing.sm,
  },
  laudosSectionCopy: {
    flex: 1,
    gap: 2,
  },
  laudosSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  laudosSectionEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  laudosSectionTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  laudosRail: {
    gap: spacing.sm,
    paddingRight: spacing.sm,
  },
  laudoChip: {
    width: 196,
    backgroundColor: colors.surfacePanelRaised,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    padding: spacing.md,
    gap: spacing.xs,
    ...shadows.soft,
  },
  laudoChipTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  laudoChipEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  laudoChipEyebrowActive: {
    color: colors.accentSoft,
  },
  laudoChipActive: {
    backgroundColor: colors.ink800,
    borderColor: colors.ink800,
  },
  laudoChipTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  laudoChipTitleActive: {
    color: colors.white,
  },
  laudoChipPreview: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    minHeight: 36,
  },
  laudoChipPreviewActive: {
    color: "rgba(255,255,255,0.82)",
  },
  laudoChipMeta: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "600",
  },
  laudoChipMetaActive: {
    color: "rgba(255,255,255,0.66)",
  },
  laudoChipStatus: {
    alignSelf: "flex-start",
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    marginTop: spacing.xs,
  },
  laudoChipStatusText: {
    fontSize: 11,
    fontWeight: "700",
  },
  activityStrip: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    backgroundColor: colors.surfacePanelRaised,
    padding: spacing.md,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    ...shadows.soft,
  },
  activityStripIcon: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    backgroundColor: "rgba(244,123,32,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  activityStripCopy: {
    flex: 1,
    gap: 2,
  },
  activityStripTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  activityStripBody: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  activityStripTime: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
  },
  offlineReadBanner: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.accentMuted,
    backgroundColor: colors.accentWash,
    padding: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  offlineReadBannerIcon: {
    width: 36,
    height: 36,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  offlineReadBannerCopy: {
    flex: 1,
    gap: 2,
  },
  offlineReadBannerTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  offlineReadBannerText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  offlineQueueCard: {
    gap: spacing.sm,
    backgroundColor: colors.surfaceCanvas,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.accentMuted,
    padding: spacing.md,
    ...shadows.soft,
  },
  offlineQueueHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  offlineQueueActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  offlineQueueCopy: {
    flex: 1,
    gap: 2,
  },
  offlineQueueTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  offlineQueueDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  offlineQueueSummaryChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  offlineQueueSummaryChip: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radii.pill,
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  offlineQueueSummaryChipAccent: {
    backgroundColor: colors.accentWash,
    borderColor: colors.accentMuted,
  },
  offlineQueueSummaryChipDanger: {
    backgroundColor: colors.dangerWash,
    borderColor: colors.dangerSoft,
  },
  offlineQueueSummaryChipText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  offlineQueueSummaryChipTextAccent: {
    color: colors.accent,
  },
  offlineQueueSummaryChipTextDanger: {
    color: colors.danger,
  },
  offlineQueueSyncButton: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.accentMuted,
  },
  offlineQueueOpenButton: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.accentMuted,
  },
  offlineQueueSyncButtonDisabled: {
    opacity: 0.55,
  },
  offlineQueueItems: {
    gap: spacing.xs,
  },
  offlineQueueItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    backgroundColor: colors.surfacePanelRaised,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    paddingHorizontal: spacing.sm,
    paddingVertical: 10,
  },
  offlineQueueItemContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  offlineQueueItemBadge: {
    width: 32,
    height: 32,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accentWash,
  },
  offlineQueueItemCopy: {
    flex: 1,
    gap: 2,
  },
  offlineQueueItemTitle: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
  },
  offlineQueueItemText: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  offlineQueueItemMeta: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  offlineQueueItemRemove: {
    width: 28,
    height: 28,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  offlineQueueFooter: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  offlineModalToolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceCanvas,
    borderWidth: 1,
    borderColor: colors.accentMuted,
  },
  offlineModalToolbarText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  offlineModalSyncButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.accentMuted,
  },
  offlineModalSyncButtonDisabled: {
    opacity: 0.55,
  },
  offlineModalSyncText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "700",
  },
  offlineModalSyncTextDisabled: {
    color: colors.textSecondary,
  },
  offlineModalFilters: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  offlineModalFilterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.surfacePanel,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  offlineModalFilterChipActive: {
    backgroundColor: colors.ink800,
    borderColor: colors.ink800,
  },
  offlineModalFilterText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  offlineModalFilterTextActive: {
    color: colors.white,
  },
  offlineModalFilterCount: {
    minWidth: 24,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  offlineModalFilterCountActive: {
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  offlineModalFilterCountText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  offlineModalFilterCountTextActive: {
    color: colors.white,
  },
  offlineModalItem: {
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: radii.lg,
    backgroundColor: colors.surfacePanel,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    ...shadows.soft,
  },
  offlineModalItemTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  offlineModalItemBadge: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accentWash,
  },
  offlineModalItemCopy: {
    flex: 1,
    gap: 4,
  },
  offlineModalItemHeading: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  offlineModalItemTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  offlineModalItemTime: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  offlineModalItemText: {
    color: colors.textPrimary,
    fontSize: 13,
    lineHeight: 19,
  },
  offlineModalItemHint: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  offlineModalItemStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    flexWrap: "wrap",
  },
  offlineModalItemStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radii.pill,
    backgroundColor: colors.accentWash,
  },
  offlineModalItemStatusBadgeError: {
    backgroundColor: colors.dangerWash,
  },
  offlineModalItemStatusBadgeText: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
  },
  offlineModalItemStatusBadgeTextError: {
    color: colors.danger,
  },
  offlineModalItemStatusText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  offlineModalItemActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: spacing.xs,
    flexWrap: "wrap",
  },
  offlineModalActionGhost: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radii.pill,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#FFD6B2",
  },
  offlineModalActionGhostDisabled: {
    opacity: 0.55,
  },
  offlineModalActionGhostText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "700",
  },
  offlineModalActionGhostTextDisabled: {
    color: colors.textSecondary,
  },
  offlineModalActionPrimary: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radii.pill,
    backgroundColor: colors.accent,
  },
  offlineModalActionPrimaryText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "800",
  },
  offlineModalActionSecondary: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceSoft,
  },
  offlineModalActionSecondaryText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  laudoStatusBadge: {
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
  },
  laudoStatusText: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  reopenButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: "#FFF5ED",
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
  },
  reopenButtonText: {
    color: colors.accent,
    fontWeight: "700",
  },
  threadBody: {
    flex: 1,
    minHeight: 0,
    backgroundColor: colors.surfaceCanvas,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.xs,
    ...shadows.card,
  },
  threadBodyKeyboardVisible: {
    paddingTop: spacing.sm,
  },
  threadEmptyState: {
    flex: 1,
    minHeight: 220,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
  },
  threadEmptyStateKeyboardVisible: {
    minHeight: 148,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  threadScroll: {
    flex: 1,
  },
  threadEmptyBrandStage: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.md,
  },
  threadEmptyBrandHalo: {
    position: "absolute",
    top: -12,
    width: 122,
    height: 122,
    borderRadius: 61,
    backgroundColor: "rgba(244,123,32,0.08)",
  },
  threadEmptyBrandMark: {
    width: 88,
    height: 88,
    borderRadius: 28,
    shadowColor: colors.ink900,
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  threadEmptyBrand: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1.4,
    marginTop: -2,
  },
  threadEmptyTitle: {
    color: colors.textPrimary,
    fontSize: 23,
    fontWeight: "800",
    textAlign: "center",
    lineHeight: 31,
    maxWidth: 300,
  },
  threadEmptyText: {
    color: colors.textSecondary,
    fontSize: 15,
    lineHeight: 23,
    textAlign: "center",
    maxWidth: 300,
  },
  threadEmptySuggestionRail: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  threadEmptySuggestion: {
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: "#FFD9BC",
    backgroundColor: "#FFF8F1",
  },
  threadEmptySuggestionText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "700",
  },
  threadContent: {
    flexGrow: 1,
    paddingTop: spacing.xs,
    paddingBottom: spacing.md,
    gap: spacing.md,
  },
  threadContentKeyboard: {
    paddingTop: 2,
    paddingBottom: spacing.sm,
    gap: spacing.sm,
  },
  messageRow: {
    width: "100%",
  },
  messageRowIncoming: {
    alignItems: "flex-start",
  },
  messageRowOutgoing: {
    alignItems: "flex-end",
  },
  messageIncomingCluster: {
    maxWidth: "94%",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  messageAvatar: {
    width: 38,
    height: 38,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    marginBottom: 8,
  },
  messageAvatarTariel: {
    backgroundColor: "#EEF5FB",
    borderColor: "#D9E6F2",
  },
  messageAvatarBrand: {
    width: 40,
    height: 40,
    borderRadius: 12,
    marginBottom: 8,
  },
  messageAvatarEngineering: {
    backgroundColor: "#FFF4E8",
    borderColor: "#EEC8A7",
  },
  messageAvatarMesa: {
    backgroundColor: "#FFF4E8",
    borderColor: "#EEC8A7",
  },
  messageBubble: {
    maxWidth: "86%",
    borderRadius: 24,
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    gap: 10,
  },
  messageBubbleIncomingShell: {
    flexShrink: 1,
    maxWidth: "100%",
  },
  messageBubbleIncoming: {
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 12,
    ...shadows.soft,
  },
  messageBubbleOutgoing: {
    backgroundColor: colors.ink900,
    borderWidth: 1,
    borderColor: colors.ink800,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 12,
    ...shadows.card,
  },
  messageBubbleEngineering: {
    backgroundColor: colors.accentWash,
    borderWidth: 1,
    borderColor: colors.accentMuted,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 12,
    ...shadows.soft,
  },
  messageBubbleReferenced: {
    borderColor: colors.accentMuted,
    borderWidth: 1,
  },
  messageAuthor: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  messageAuthorOutgoing: {
    color: colors.accentSoft,
  },
  messageHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  messageStatusBadge: {
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: radii.pill,
    borderWidth: 1,
  },
  messageStatusBadgeAccent: {
    backgroundColor: "#FFF1E4",
    borderColor: "#FFD6B2",
  },
  messageStatusBadgeSuccess: {
    backgroundColor: "#EEF9F3",
    borderColor: "#BCE8D0",
  },
  messageStatusBadgeText: {
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  messageStatusBadgeTextAccent: {
    color: colors.accent,
  },
  messageStatusBadgeTextSuccess: {
    color: colors.success,
  },
  messageText: {
    color: colors.textPrimary,
    fontSize: 15,
    lineHeight: 23,
  },
  messageTextOutgoing: {
    color: colors.white,
  },
  messageMeta: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  messageMetaOutgoing: {
    color: "rgba(255,255,255,0.74)",
    alignSelf: "flex-end",
  },
  messageReferenceCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfaceSoft,
    paddingHorizontal: spacing.sm,
    paddingVertical: 10,
  },
  messageReferenceCardOutgoing: {
    borderColor: "rgba(255,255,255,0.24)",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  messageReferenceIcon: {
    width: 24,
    height: 24,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accentWash,
  },
  messageReferenceIconOutgoing: {
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  messageReferenceCopy: {
    flex: 1,
    gap: 2,
  },
  messageReferenceTitle: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  messageReferenceTitleOutgoing: {
    color: "rgba(255,255,255,0.86)",
  },
  messageReferenceText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  messageReferenceTextOutgoing: {
    color: "rgba(255,255,255,0.8)",
  },
  messageActionRow: {
    paddingTop: 2,
  },
  messageActionButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
  },
  messageActionText: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "700",
  },
  messageAttachments: {
    gap: spacing.xs,
  },
  messageAttachmentCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: colors.surfaceSoft,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    padding: spacing.sm,
  },
  messageAttachmentCardDisabled: {
    opacity: 0.7,
  },
  messageAttachmentIconCircle: {
    width: 38,
    height: 38,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accentWash,
  },
  messageAttachmentImagePreview: {
    width: 52,
    height: 52,
    borderRadius: radii.sm,
    backgroundColor: "#E8EDF2",
  },
  messageAttachmentBody: {
    flex: 1,
    gap: 2,
  },
  messageAttachmentTitle: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "600",
  },
  messageAttachmentCaption: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  messageAttachmentAction: {
    width: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  typingRow: {
    alignItems: "flex-start",
  },
  typingBubble: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: colors.surfaceSoft,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  typingText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "600",
  },
  composerCard: {
    backgroundColor: colors.surfacePanelRaised,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
    gap: spacing.xs,
    ...shadows.soft,
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  composerCardKeyboardVisible: {
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
    gap: spacing.xs,
  },
  composerHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  composerHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  composerEyebrow: {
    color: colors.textMuted,
    ...typography.eyebrow,
  },
  composerTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
  },
  composerSubtitle: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  composerStatusBadge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
  },
  composerStatusBadgeAccent: {
    backgroundColor: colors.accentWash,
    borderColor: colors.accentMuted,
  },
  composerStatusBadgeSuccess: {
    backgroundColor: colors.successWash,
    borderColor: colors.successSoft,
  },
  composerStatusBadgeText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  composerStatusBadgeTextAccent: {
    color: colors.accent,
  },
  composerStatusBadgeTextSuccess: {
    color: colors.success,
  },
  composerHint: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 17,
    paddingHorizontal: 2,
  },
  composerToolsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    flexWrap: "wrap",
  },
  composerToolsLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  composerToolsText: {
    color: colors.textSecondary,
    fontSize: 12,
    flex: 1,
    textAlign: "left",
    minWidth: 180,
  },
  attachButton: {
    width: 42,
    height: 42,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  attachButtonDisabled: {
    opacity: 0.45,
  },
  attachmentDraftCard: {
    backgroundColor: colors.surfaceCanvas,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    padding: spacing.md,
    ...shadows.soft,
  },
  attachmentDraftHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  attachmentDraftIcon: {
    width: 36,
    height: 36,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accentWash,
  },
  attachmentDraftPreview: {
    width: 52,
    height: 52,
    borderRadius: radii.sm,
    backgroundColor: "#E8EDF2",
  },
  attachmentDraftCopy: {
    flex: 1,
    gap: 2,
  },
  attachmentDraftTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  attachmentDraftDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  attachmentDraftRemove: {
    width: 30,
    height: 30,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  composerReferenceCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    backgroundColor: colors.surfaceCanvas,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    ...shadows.soft,
  },
  composerReferenceCopy: {
    flex: 1,
    gap: 2,
  },
  composerReferenceTitle: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  composerReferenceText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  composerReferenceRemove: {
    width: 28,
    height: 28,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
} as const;
