import { colors, radii, spacing } from "../../theme/tokens";

export const historyStyles = {
  historyModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(9,16,25,0.14)",
    padding: spacing.md,
    justifyContent: "flex-end",
  },
  historyModalCard: {
    backgroundColor: "#FFFDF9",
    borderRadius: 30,
    padding: spacing.lg,
    gap: spacing.md,
    maxHeight: "82%",
    shadowColor: colors.ink900,
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  historyModalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  historyBrandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginBottom: 2,
  },
  historyBrandIcon: {
    width: 28,
    height: 28,
    borderRadius: 10,
  },
  historyBrandEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  historyModalCopy: {
    flex: 1,
    gap: 4,
  },
  historyModalTitle: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: "800",
  },
  historyModalSubtitle: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  historyModalClose: {
    width: 40,
    height: 40,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF8F1",
    borderWidth: 1,
    borderColor: "#E8D8C9",
  },
  historySearchShell: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E8D8C9",
    backgroundColor: "#FFF8F1",
  },
  historySearchInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 16,
    paddingVertical: 12,
  },
  historySummaryCard: {
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#E8D8C9",
    borderTopColor: "#F0B98B",
    borderTopWidth: 1.5,
    backgroundColor: "#FFF8F1",
  },
  historySummaryMetrics: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  historySummaryMetric: {
    flex: 1,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    borderRadius: 18,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#EADFD4",
    gap: 2,
  },
  historySummaryMetricValue: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "800",
  },
  historySummaryMetricLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  historySummaryText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  historyFilterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  historyFilterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  historyFilterChipActive: {
    backgroundColor: "#FFF1E4",
    borderColor: "#FFD6B2",
  },
  historyFilterChipText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  historyFilterChipTextActive: {
    color: colors.accent,
  },
  historyFilterCount: {
    minWidth: 24,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  historyFilterCountActive: {
    backgroundColor: colors.accent,
  },
  historyFilterCountText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  historyFilterCountTextActive: {
    color: colors.white,
  },
  historySections: {
    gap: spacing.lg,
    paddingBottom: spacing.lg,
  },
  historySection: {
    gap: spacing.sm,
  },
  historySectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  historySectionTitle: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  historySectionCountBadge: {
    minWidth: 26,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF1E4",
    borderWidth: 1,
    borderColor: "#FFD6B2",
  },
  historySectionCountText: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
  },
  historySectionItems: {
    gap: spacing.sm,
  },
  historyItemShell: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: spacing.xs,
  },
  historyItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#E7DDD2",
    backgroundColor: "#FFFDFB",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    shadowColor: colors.ink900,
    shadowOpacity: 0.035,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 2,
  },
  historyItemPrimary: {
    flex: 1,
  },
  historyItemActive: {
    backgroundColor: colors.ink800,
    borderColor: colors.ink800,
    shadowOpacity: 0.08,
    elevation: 4,
  },
  historyItemActions: {
    justifyContent: "center",
    gap: spacing.xs,
  },
  historyItemActionButton: {
    width: 42,
    height: 42,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF4E8",
    borderWidth: 1,
    borderColor: "#E7DDD2",
    shadowColor: colors.ink900,
    shadowOpacity: 0.025,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  historyItemActionButtonPinned: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  historyItemActionButtonDanger: {
    backgroundColor: "#FFF8F4",
    borderColor: "#EBD5CA",
  },
  historyItemIcon: {
    width: 42,
    height: 42,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF8F1",
    borderWidth: 1,
    borderColor: "#E7DDD2",
  },
  historyItemIconActive: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.18)",
  },
  historyItemBrandIcon: {
    width: 26,
    height: 26,
    borderRadius: 8,
  },
  historyItemCopy: {
    flex: 1,
    gap: 4,
  },
  historyItemMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    flexWrap: "wrap",
  },
  historyItemInfoTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: radii.pill,
    backgroundColor: "#FFF7EF",
    borderWidth: 1,
    borderColor: "#E7DDD2",
  },
  historyItemInfoTagEditable: {
    backgroundColor: "#EEF9F3",
    borderColor: "#BCE8D0",
  },
  historyItemInfoTagActive: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.14)",
  },
  historyItemInfoTagText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
  },
  historyItemInfoTagTextEditable: {
    color: colors.success,
  },
  historyItemInfoTagTextActive: {
    color: colors.white,
  },
  historyItemHeading: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  historyItemTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  historyItemTitleActive: {
    color: colors.white,
  },
  historyItemTime: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  historyItemTimeActive: {
    color: "rgba(255,255,255,0.72)",
  },
  historyItemPreview: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  historyItemPreviewActive: {
    color: "rgba(255,255,255,0.84)",
  },
  historyItemStatus: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  historyItemStatusAccent: {
    backgroundColor: "#FFF1E4",
    borderColor: "#FFD6B2",
  },
  historyItemStatusSuccess: {
    backgroundColor: "#EEF9F3",
    borderColor: "#BCE8D0",
  },
  historyItemStatusDanger: {
    backgroundColor: "#FDEEEE",
    borderColor: "#F6CACA",
  },
  historyItemStatusActive: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.18)",
  },
  historyItemStatusText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  historyItemStatusTextAccent: {
    color: colors.accent,
  },
  historyItemStatusTextSuccess: {
    color: colors.success,
  },
  historyItemStatusTextDanger: {
    color: colors.danger,
  },
  historyItemStatusTextActive: {
    color: colors.white,
  },
  historyItemPinnedTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: radii.pill,
    backgroundColor: "#FFF8F1",
    borderWidth: 1,
    borderColor: "#E9D9C8",
  },
  historyItemPinnedTagActive: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.18)",
  },
  historyItemPinnedTagText: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
  },
  historyItemPinnedTagTextActive: {
    color: colors.white,
  },
  historyEmptyState: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    paddingVertical: spacing.xxl,
  },
  historyEmptyBrand: {
    width: 56,
    height: 56,
    borderRadius: 18,
  },
  historyEmptyTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  historyEmptyText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
} as const;
