import {
  colors,
  radii,
  shadows,
  spacing,
  typography,
} from "../../theme/tokens";

export const historyStyles = {
  historyModalBackdrop: {
    flex: 1,
    backgroundColor: colors.overlaySoft,
    padding: spacing.md,
    justifyContent: "flex-end",
  },
  historyModalCard: {
    backgroundColor: colors.surfacePanel,
    borderRadius: radii.xl,
    padding: spacing.lg,
    gap: spacing.md,
    maxHeight: "82%",
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    ...shadows.floating,
  },
  historyModalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  historyBrandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginBottom: 2,
  },
  historyBrandIcon: {
    width: 28,
    height: 28,
    borderRadius: 10,
  },
  historyBrandEyebrow: {
    color: colors.textMuted,
    ...typography.eyebrow,
  },
  historyModalCopy: {
    flex: 1,
    gap: 4,
  },
  historyModalTitle: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: "800",
  },
  historyModalSubtitle: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  historyModalClose: {
    width: 40,
    height: 40,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceCanvas,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
  },
  historySearchShell: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfaceSoft,
  },
  historySearchInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 15,
    paddingVertical: 11,
  },
  historySummaryCard: {
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfaceSoft,
  },
  historySummaryMetrics: {
    flexDirection: "row",
    gap: spacing.xs,
  },
  historySummaryMetric: {
    flex: 1,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    borderRadius: 16,
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    gap: 2,
  },
  historySummaryMetricValue: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: "800",
  },
  historySummaryMetricLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  historySummaryText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  historyFilterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    padding: 4,
    borderRadius: 18,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  historyFilterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: spacing.sm,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: "transparent",
  },
  historyFilterChipActive: {
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  historyFilterChipText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  historyFilterChipTextActive: {
    color: colors.textPrimary,
  },
  historyFilterCount: {
    minWidth: 24,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfacePanelRaised,
  },
  historyFilterCountActive: {
    backgroundColor: colors.accentWash,
  },
  historyFilterCountText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  historyFilterCountTextActive: {
    color: colors.accent,
  },
  historySections: {
    gap: spacing.lg,
    paddingBottom: spacing.lg,
  },
  historySection: {
    gap: spacing.sm,
  },
  historySectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  historySectionTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  historySectionCountBadge: {
    minWidth: 26,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  historySectionCountText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  historySectionItems: {
    gap: spacing.sm,
  },
  historyItemShell: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 18,
  },
  historyItemDeleteRail: {
    ...shadows.soft,
    position: "absolute",
    inset: 0,
    borderRadius: 18,
    backgroundColor: colors.dangerWash,
    borderWidth: 1,
    borderColor: colors.dangerSoft,
    alignItems: "flex-start",
    justifyContent: "center",
    paddingHorizontal: spacing.md,
  },
  historyItemDeleteRailBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.dangerSoft,
  },
  historyItemDeleteRailText: {
    color: colors.danger,
    fontSize: 12,
    fontWeight: "800",
  },
  historyItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  historyItemPrimary: {
    width: "100%",
  },
  historyItemActive: {
    backgroundColor: colors.ink800,
    borderColor: colors.ink800,
    ...shadows.card,
  },
  historyItemCopy: {
    flex: 1,
    gap: 4,
  },
  historyItemTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  historyItemTitleActive: {
    color: colors.white,
  },
  historyItemPreview: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  historyItemPreviewActive: {
    color: "rgba(255,255,255,0.84)",
  },
  historyEmptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: spacing.xxl,
  },
  historyEmptyBrand: {
    width: 56,
    height: 56,
    borderRadius: 18,
  },
  historyEmptyTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  historyEmptyText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
} as const;
