import { colors, componentSizes, radii, shadows, spacing, typography } from "../../theme/tokens";

export const loginStyles = {
  loginScrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xxl,
  },
  loginScrollContentKeyboardVisible: {
    justifyContent: "flex-start",
    paddingTop: spacing.xl,
    paddingBottom: spacing.xl,
  },
  loginScreen: {
    gap: spacing.lg,
  },
  loginBrand: {
    alignItems: "center",
    gap: spacing.xs,
    paddingBottom: spacing.xs,
  },
  brandStageCompact: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
  },
  brandHaloCompact: {
    position: "absolute",
    top: -8,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "rgba(244,123,32,0.05)",
  },
  brandMarkCompact: {
    width: 76,
    height: 76,
    borderRadius: 22,
    ...shadows.soft,
  },
  brandLabelCompact: {
    color: colors.ink600,
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 2.2,
  },
  loginCard: {
    backgroundColor: colors.surfacePanel,
    borderRadius: 28,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
    paddingBottom: spacing.xl,
    gap: spacing.lg,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    ...shadows.card,
  },
  loginCardHeader: {
    gap: 6,
  },
  loginCardEyebrow: {
    color: colors.textMuted,
    ...typography.eyebrow,
  },
  loginCardTitle: {
    color: colors.textPrimary,
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "800",
  },
  loginCardSubtitle: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  loginFields: {
    gap: spacing.xs,
  },
  mobileField: {
    minHeight: componentSizes.controlLg,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfaceSoft,
    paddingHorizontal: spacing.md,
  },
  mobileFieldInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 16,
    paddingVertical: 15,
  },
  mobileFieldAction: {
    width: 32,
    height: 32,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  loginForgotRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  loginMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  loginRememberRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  loginCheckbox: {
    width: 18,
    height: 18,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#CAD6E2",
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  loginCheckboxActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  loginRememberText: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  loginForgotLink: {
    color: colors.ink700,
    fontSize: 13,
    fontWeight: "700",
  },
  loginPrimaryButton: {
    minHeight: 54,
    borderRadius: 16,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    ...shadows.accent,
  },
  loginPrimaryButtonText: {
    color: colors.white,
    fontSize: 17,
    fontWeight: "800",
  },
  loginDividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  loginDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.surfaceStroke,
  },
  loginDividerText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
  },
  loginSocialStack: {
    gap: spacing.xs,
  },
  loginSocialButton: {
    minHeight: 50,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  loginSocialIconShell: {
    width: 32,
    height: 32,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  loginSocialButtonText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  loginFooterText: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
} as const;
