import { colors, radii, spacing } from "../../theme/tokens";

export const loginStyles = {
  loginScrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xxl,
  },
  loginScrollContentKeyboardVisible: {
    justifyContent: "flex-start",
    paddingTop: spacing.xl,
    paddingBottom: spacing.xl,
  },
  loginScreen: {
    gap: spacing.xl,
  },
  loginBrand: {
    alignItems: "center",
    gap: spacing.sm,
    paddingBottom: spacing.sm,
  },
  brandStageCompact: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
  },
  brandHaloCompact: {
    position: "absolute",
    top: -10,
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: "rgba(244,123,32,0.06)",
  },
  brandMarkCompact: {
    width: 92,
    height: 92,
    borderRadius: 28,
    shadowColor: colors.ink900,
    shadowOpacity: 0.14,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  brandLabelCompact: {
    color: colors.textSecondary,
    fontSize: 16,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 2.4,
  },
  loginCard: {
    backgroundColor: "#FFFDFC",
    borderRadius: 32,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
    paddingBottom: spacing.xxl,
    gap: spacing.lg,
    borderWidth: 1,
    borderColor: "rgba(231,216,200,0.96)",
    shadowColor: colors.ink900,
    shadowOpacity: 0.08,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 8,
  },
  loginFields: {
    gap: spacing.md,
  },
  mobileField: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: "#FFFCF8",
    paddingHorizontal: spacing.md,
  },
  mobileFieldInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 17,
    paddingVertical: 16,
  },
  mobileFieldAction: {
    width: 32,
    height: 32,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
  },
  loginForgotRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  loginMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  loginRememberRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  loginCheckbox: {
    width: 18,
    height: 18,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#CAD6E2",
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  loginCheckboxActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  loginRememberText: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  loginForgotLink: {
    color: colors.ink600,
    fontSize: 13,
    fontWeight: "700",
  },
  loginPrimaryButton: {
    minHeight: 58,
    borderRadius: 20,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.accent,
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  loginPrimaryButtonText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: "800",
  },
  loginDividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  loginDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#E5ECF3",
  },
  loginDividerText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "600",
  },
  loginSocialStack: {
    gap: spacing.sm,
  },
  loginSocialLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  loginSocialButton: {
    minHeight: 50,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: "#FFFDFC",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  loginSocialIconShell: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  loginSocialButtonText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  loginFooterText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
} as const;
