import { buildSettingsDrawerPanelProps } from "./buildSettingsDrawerPanelProps";

type BuildInspectorSettingsDrawerPanelPropsInput = Record<string, any>;

export function buildInspectorSettingsDrawerPanelProps(
  input: BuildInspectorSettingsDrawerPanelPropsInput,
): ReturnType<typeof buildSettingsDrawerPanelProps> {
  const {
    accountSectionContentProps,
    advancedResourcesSectionProps,
    aprendizadoIa,
    analyticsOptIn,
    animacoesAtivas,
    arquivosPermitidos,
    artigosAjudaFiltrados,
    autoUploadAttachments,
    backupAutomatico,
    biometriaPermitida,
    cameraPermitida,
    cartaoAtual,
    codigo2FA,
    codigosRecuperacao,
    criticalAlertsEnabled,
    compartilharMelhoriaIa,
    configuracoesDrawerX,
    contaEmailLabel,
    contaTelefoneLabel,
    conversasOcultasTotal,
    conversasVisiveisTotal,
    corDestaque,
    corDestaqueResumoConfiguracao,
    densidadeInterface,
    deviceBiometricsEnabled,
    economiaDados,
    email,
    emailAtualConta,
    emailsAtivos,
    entradaPorVoz,
    estiloResposta,
    experienceNotificationsSectionProps,
    eventosSegurancaFiltrados,
    existeProvedorDisponivel,
    fecharConfiguracoes,
    filaSuporteLocal,
    filtroEventosSeguranca,
    fixarConversas,
    handleAbrirAjustesDoSistema,
    handleAbrirCentralAtividade,
    handleAbrirCanalSuporte,
    handleAbrirPaginaConfiguracoes,
    handleAbrirSobreApp,
    handleAbrirSecaoConfiguracoes,
    handleAbrirAjudaDitado,
    handleAlterarEmail,
    handleEditarPerfil,
    handleAlterarSenha,
    handleApagarHistoricoConfiguracoes,
    handleCentralAjuda,
    handleCompartilharCodigosRecuperacao,
    handleConectarProximoProvedorDisponivel,
    handleConfirmarCodigo2FA,
    handleDetalhesSegurancaArquivos,
    handleEncerrarOutrasSessoes,
    handleEncerrarSessao,
    handleEncerrarSessaoAtual,
    handleEncerrarSessoesSuspeitas,
    handleEnviarFeedback,
    handleExcluirConta,
    handleExportarAntesDeExcluirConta,
    handleExportarDados,
    handleExportarDiagnosticoApp,
    handleGerarCodigosRecuperacao,
    handleGerenciarConversasIndividuais,
    handleGerenciarPagamento,
    handleGerenciarPermissao,
    handleGerenciarPlano,
    handleHistoricoPagamentos,
    handleIntegracoesExternas,
    handleLicencas,
    handleLimparCache,
    handleLimparFilaSuporteLocal,
    handleLimparTodasConversasConfig,
    handleLogout,
    handleSolicitarLogout,
    handleAbrirModeloIa,
    handleMudarMetodo2FA,
    handlePermissoes,
    handlePluginsIa,
    handlePoliticaPrivacidade,
    handleReautenticacaoSensivel,
    handleRefresh,
    handleReportarAtividadeSuspeita,
    handleReportarProblema,
    handleRevisarPermissoesCriticas,
    handleRevisarSessao,
    handleTermosUso,
    handleToggle2FA,
    handleToggleBackupAutomatico,
    handleToggleBiometriaNoDispositivo,
    handleToggleSpeechEnabled,
    handleToggleEntradaPorVoz,
    handleToggleMostrarConteudoNotificacao,
    handleToggleMostrarSomenteNovaMensagem,
    handleToggleNotificaPush,
    handleToggleOcultarConteudoBloqueado,
    handleToggleProviderConnection,
    handleToggleRespostaPorVoz,
    handleToggleSincronizacaoDispositivos,
    handleToggleUploadArquivos,
    handleToggleVibracao,
    handleUploadFotoPerfil,
    handleVerificarAtualizacoes,
    handleVoltarResumoConfiguracoes,
    hideInMultitask,
    idiomaApp,
    idiomaResposta,
    iniciaisPerfilConfiguracao,
    integracoesConectadasTotal,
    integracoesDisponiveisTotal,
    limpandoCache,
    lockTimeout,
    memoriaIa,
    mediaCompression,
    mesaCategoryEnabled,
    microfonePermitido,
    modeloIa,
    mostrarConteudoNotificacao,
    mostrarGrupoContaAcesso,
    mostrarGrupoExperiencia,
    mostrarGrupoSeguranca,
    mostrarGrupoSistema,
    mostrarSomenteNovaMensagem,
    nomeAutomaticoConversas,
    nomeUsuarioExibicao,
    notificaPush,
    notificaRespostas,
    notificacoesPermitidas,
    preferredVoiceLabel,
    ocultarConteudoBloqueado,
    onAbrirFilaOffline,
    outrasSessoesAtivas,
    perfilExibicao,
    perfilExibicaoLabel,
    perfilFotoHint,
    perfilFotoUri,
    perfilNome,
    perfilNomeCompleto,
    permissoesNegadasTotal,
    planoAtual,
    planoResumoConfiguracao,
    previewPrivacidadeNotificacao,
    provedoresConectados,
    provedoresConectadosTotal,
    provedorPrimario,
    reautenticacaoStatus,
    recoveryCodesEnabled,
    regiaoApp,
    requireAuthOnOpen,
    resumoCache,
    resumoCentralAtividade,
    respostaPorVoz,
    crashReportsOptIn,
    resumo2FAFootnote,
    resumo2FAStatus,
    resumoAlertaMetodosConta,
    resumoBlindagemSessoes,
    resumoContaAcesso,
    resumoCodigosRecuperacao,
    resumoDadosConversas,
    resumoExcluirConta,
    resumoFilaSuporteLocal,
    resumoMetodosConta,
    resumoPermissoes,
    resumoPermissoesCriticas,
    resumoPrivacidadeNotificacoes,
    resumoSessaoAtual,
    resumoSuporteApp,
    retencaoDados,
    salvarHistoricoConversas,
    setAnimacoesAtivas,
    setAprendizadoIa,
    setAnalyticsOptIn,
    setCodigo2FA,
    setCompartilharMelhoriaIa,
    setCrashReportsOptIn,
    setCorDestaque,
    setDensidadeInterface,
    setEconomiaDados,
    setEmailsAtivos,
    setEstiloResposta,
    setFiltroEventosSeguranca,
    setFixarConversas,
    setHideInMultitask,
    setIdiomaApp,
    setIdiomaResposta,
    setLockTimeout,
    setMemoriaIa,
    setNomeAutomaticoConversas,
    setNotificaRespostas,
    setPerfilExibicao,
    setPerfilNome,
    setRecoveryCodesEnabled,
    setRegiaoApp,
    setRequireAuthOnOpen,
    setRetencaoDados,
    setSalvarHistoricoConversas,
    setSomNotificacao,
    setSpeechEnabled,
    setTamanhoFonte,
    setTemperaturaIa,
    setTemaApp,
    setTomConversa,
    setUsoBateria,
    setVoiceLanguage,
    setSpeechRate,
    setChatCategoryEnabled,
    setMesaCategoryEnabled,
    setSystemCategoryEnabled,
    setCriticalAlertsEnabled,
    setAutoUploadAttachments,
    setMediaCompression,
    setWifiOnlySync,
    settingsDrawerInOverview,
    settingsDrawerMatchesPage,
    settingsDrawerMatchesSection,
    settingsDrawerPage,
    settingsDrawerPageSections,
    settingsDrawerPanResponder,
    settingsDrawerSectionMenuAtiva,
    settingsDrawerSubtitle,
    settingsDrawerTitle,
    settingsPrintDarkMode,
    sessoesAtivas,
    sessoesSuspeitasTotal,
    sincronizacaoDispositivos,
    somNotificacao,
    speechEnabled,
    speechRate,
    sttSupported,
    systemCategoryEnabled,
    tamanhoFonte,
    temperaturaIa,
    temaApp,
    temaResumoConfiguracao,
    temPrioridadesConfiguracao,
    ticketsBugTotal,
    ticketsFeedbackTotal,
    tomConversa,
    totalSecoesConfiguracaoVisiveis,
    twoFactorEnabled,
    twoFactorMethod,
    ultimaVerificacaoAtualizacaoLabel,
    ultimoEventoProvedor,
    ultimoEventoSessao,
    ultimoTicketSuporteResumo,
    uploadArquivosAtivo,
    usoBateria,
    vibracaoAtiva,
    verificandoAtualizacoes,
    voiceLanguage,
    supportChannelLabel,
    ttsSupported,
    wifiOnlySync,
    workspaceResumoConfiguracao,
    chatCategoryEnabled,
    sincronizandoDados,
    onCyclePreferredVoice,
    onAbrirPermissaoNotificacoes,
  } = input;

  return buildSettingsDrawerPanelProps({
    accountSectionContentProps: accountSectionContentProps || {
      contaEmailLabel,
      contaTelefoneLabel,
      onEditarPerfil: handleEditarPerfil,
      onAlterarEmail: handleAlterarEmail,
      onAlterarSenha: handleAlterarSenha,
      onSolicitarLogout: handleSolicitarLogout,
      onUploadFotoPerfil: handleUploadFotoPerfil,
      perfilExibicaoLabel,
      perfilFotoHint,
      perfilFotoUri,
      perfilNomeCompleto,
      provedorPrimario,
      resumoConta: resumoContaAcesso,
      workspaceAtual: workspaceResumoConfiguracao,
    },
    advancedResourcesSectionProps: advancedResourcesSectionProps || {
      speechEnabled,
      entradaPorVoz,
      microfonePermitido,
      onAbrirAjudaDitado: handleAbrirAjudaDitado,
      onAbrirAjustesDoSistema: () =>
        handleAbrirAjustesDoSistema("recursos de voz, acessibilidade e permissões de áudio"),
      onCyclePreferredVoice,
      onSetSpeechRate: setSpeechRate,
      onSetVoiceLanguage: setVoiceLanguage,
      onToggleSpeechEnabled: handleToggleSpeechEnabled,
      onToggleEntradaPorVoz: handleToggleEntradaPorVoz,
      onToggleRespostaPorVoz: handleToggleRespostaPorVoz,
      preferredVoiceLabel,
      respostaPorVoz,
      speechRate,
      sttSupported,
      ttsSupported,
      voiceLanguage,
    },
    artigosAjudaCount: artigosAjudaFiltrados.length,
    configuracoesDrawerX,
    emailRetorno: emailAtualConta || email || "Defina um email na conta",
    experienceAiSectionProps: {
      aprendizadoIa,
      estiloResposta,
      idiomaResposta,
      memoriaIa,
      modeloIa,
      onAbrirMenuModeloIa: handleAbrirModeloIa,
      onSetAprendizadoIa: setAprendizadoIa,
      onSetEstiloResposta: setEstiloResposta,
      onSetIdiomaResposta: setIdiomaResposta,
      onSetMemoriaIa: setMemoriaIa,
      onSetTemperaturaIa: setTemperaturaIa,
      onSetTomConversa: setTomConversa,
      temperaturaIa,
      tomConversa,
    },
    experienceAppearanceSectionProps: {
      animacoesAtivas,
      corDestaque,
      densidadeInterface,
      onSetAnimacoesAtivas: setAnimacoesAtivas,
      onSetCorDestaque: setCorDestaque,
      onSetDensidadeInterface: setDensidadeInterface,
      onSetTamanhoFonte: setTamanhoFonte,
      onSetTemaApp: setTemaApp,
      tamanhoFonte,
      temaApp,
    },
    experienceNotificationsSectionProps: experienceNotificationsSectionProps || {
      chatCategoryEnabled,
      criticalAlertsEnabled,
      emailsAtivos,
      mesaCategoryEnabled,
      notificaPush,
      notificaRespostas,
      notificacoesPermitidas,
      onAbrirPermissaoNotificacoes,
      onSetChatCategoryEnabled: setChatCategoryEnabled,
      onSetCriticalAlertsEnabled: setCriticalAlertsEnabled,
      onSetEmailsAtivos: setEmailsAtivos,
      onSetMesaCategoryEnabled: setMesaCategoryEnabled,
      onSetNotificaRespostas: setNotificaRespostas,
      onSetSomNotificacao: setSomNotificacao,
      onSetSystemCategoryEnabled: setSystemCategoryEnabled,
      onToggleNotificaPush: handleToggleNotificaPush,
      onToggleVibracao: handleToggleVibracao,
      somNotificacao,
      systemCategoryEnabled,
      vibracaoAtiva,
    },
    fecharConfiguracoes,
    filaSuporteCount: filaSuporteLocal.length,
    handleVoltarResumoConfiguracoes,
    mostrarGrupoContaAcesso,
    mostrarGrupoExperiencia,
    mostrarGrupoSeguranca,
    mostrarGrupoSistema,
    onAbrirFilaOffline,
    overviewContentProps: {
      contaEmailLabel,
      contaTelefoneLabel,
      corDestaqueResumoConfiguracao,
      iniciaisPerfilConfiguracao,
      nomeUsuarioExibicao,
      onAbrirPaginaConfiguracoes: handleAbrirPaginaConfiguracoes,
      onFecharConfiguracoes: fecharConfiguracoes,
      onLogout: handleSolicitarLogout,
      onReportarProblema: handleReportarProblema,
      onUploadFotoPerfil: handleUploadFotoPerfil,
      perfilFotoUri,
      planoResumoConfiguracao,
      settingsPrintDarkMode,
      temaResumoConfiguracao,
      workspaceResumoConfiguracao,
    },
    priorityActionsContentProps: {
      onRevisarPermissoesCriticas: handleRevisarPermissoesCriticas,
      onVerificarAtualizacoes: handleVerificarAtualizacoes,
      permissoesNegadasTotal,
      temPrioridadesConfiguracao,
      ultimaVerificacaoAtualizacaoLabel,
    },
    sectionMenuContentProps: {
      onAbrirSecaoConfiguracoes: handleAbrirSecaoConfiguracoes,
    },
    securityActivitySectionProps: {
      eventosSegurancaFiltrados,
      filtroEventosSeguranca,
      onReportarAtividadeSuspeita: handleReportarAtividadeSuspeita,
      onSetFiltroEventosSeguranca: setFiltroEventosSeguranca,
    },
    securityConnectedAccountsSectionProps: {
      onToggleProviderConnection: handleToggleProviderConnection,
      provedoresConectados,
      provedoresConectadosTotal,
      provedorPrimario,
      resumoAlertaMetodosConta,
      ultimoEventoProvedor,
    },
    securityDataConversationsSectionProps: {
      analyticsOptIn,
      backupAutomatico,
      compartilharMelhoriaIa,
      conversasOcultasTotal,
      conversasVisiveisTotal,
      crashReportsOptIn,
      fixarConversas,
      autoUploadAttachments,
      cacheStatusLabel: resumoCache,
      nomeAutomaticoConversas,
      limpandoCache,
      mediaCompression,
      onApagarHistoricoConfiguracoes: handleApagarHistoricoConfiguracoes,
      onExportarDados: handleExportarDados,
      onGerenciarConversasIndividuais: handleGerenciarConversasIndividuais,
      onLimparCache: handleLimparCache,
      onSetAnalyticsOptIn: setAnalyticsOptIn,
      onSetCrashReportsOptIn: setCrashReportsOptIn,
      onSetMediaCompression: setMediaCompression,
      onLimparTodasConversasConfig: handleLimparTodasConversasConfig,
      onSetCompartilharMelhoriaIa: setCompartilharMelhoriaIa,
      onSetFixarConversas: setFixarConversas,
      onSetNomeAutomaticoConversas: setNomeAutomaticoConversas,
      onSetRetencaoDados: setRetencaoDados,
      onSetSalvarHistoricoConversas: setSalvarHistoricoConversas,
      onSetWifiOnlySync: setWifiOnlySync,
      onToggleAutoUploadAttachments: setAutoUploadAttachments,
      onToggleBackupAutomatico: handleToggleBackupAutomatico,
      onToggleSincronizacaoDispositivos: handleToggleSincronizacaoDispositivos,
      retencaoDados,
      resumoDadosConversas,
      salvarHistoricoConversas,
      sincronizacaoDispositivos,
      wifiOnlySync,
    },
    securityDeleteAccountSectionProps: {
      onExcluirConta: handleExcluirConta,
      onExportarAntesDeExcluirConta: handleExportarAntesDeExcluirConta,
      onReautenticacaoSensivel: handleReautenticacaoSensivel,
      reautenticacaoStatus,
      resumoExcluirConta,
    },
    securityDeviceProtectionSectionProps: {
      biometricsSupported: false,
      deviceBiometricsEnabled,
      hideInMultitask,
      lockTimeout,
      onSetHideInMultitask: setHideInMultitask,
      onSetLockTimeout: setLockTimeout,
      onSetRequireAuthOnOpen: setRequireAuthOnOpen,
      onToggleBiometriaNoDispositivo: handleToggleBiometriaNoDispositivo,
      requireAuthOnOpen,
    },
    securityFileUploadSectionProps: {
      onDetalhesSegurancaArquivos: handleDetalhesSegurancaArquivos,
    },
    securityIdentityVerificationSectionProps: {
      onReautenticacaoSensivel: handleReautenticacaoSensivel,
      reautenticacaoStatus,
    },
    securityNotificationPrivacySectionProps: {
      mostrarConteudoNotificacao,
      mostrarSomenteNovaMensagem,
      ocultarConteudoBloqueado,
      onToggleMostrarConteudoNotificacao: handleToggleMostrarConteudoNotificacao,
      onToggleMostrarSomenteNovaMensagem: handleToggleMostrarSomenteNovaMensagem,
      onToggleOcultarConteudoBloqueado: handleToggleOcultarConteudoBloqueado,
      previewPrivacidadeNotificacao,
      resumoPrivacidadeNotificacoes,
    },
    securityPermissionsSectionProps: {
      arquivosPermitidos,
      biometriaPermitida,
      cameraPermitida,
      microfonePermitido,
      notificacoesPermitidas,
      onAbrirAjustesDoSistema: handleAbrirAjustesDoSistema,
      onGerenciarPermissao: handleGerenciarPermissao,
      onRevisarPermissoesCriticas: handleRevisarPermissoesCriticas,
      permissoesNegadasTotal,
      resumoPermissoes,
      resumoPermissoesCriticas,
      showBiometricsPermission: false,
    },
    securitySessionsSectionProps: {
      onEncerrarOutrasSessoes: handleEncerrarOutrasSessoes,
      onEncerrarSessao: handleEncerrarSessao,
      onEncerrarSessaoAtual: handleEncerrarSessaoAtual,
      onEncerrarSessoesSuspeitas: handleEncerrarSessoesSuspeitas,
      onFecharConfiguracoes: fecharConfiguracoes,
      onLogout: handleLogout,
      onRevisarSessao: handleRevisarSessao,
      outrasSessoesAtivas,
      resumoBlindagemSessoes,
      resumoSessaoAtual,
      sessoesAtivas,
      sessoesSuspeitasTotal,
      ultimoEventoSessao,
    },
    securityTwoFactorSectionProps: {
      codigo2FA,
      codigosRecuperacao,
      onCompartilharCodigosRecuperacao: handleCompartilharCodigosRecuperacao,
      onConfirmarCodigo2FA: handleConfirmarCodigo2FA,
      onGerarCodigosRecuperacao: handleGerarCodigosRecuperacao,
      onMudarMetodo2FA: handleMudarMetodo2FA,
      onSetCodigo2FA: setCodigo2FA,
      onSetRecoveryCodesEnabled: setRecoveryCodesEnabled,
      onToggle2FA: handleToggle2FA,
      reautenticacaoStatus,
      recoveryCodesEnabled,
      resumo2FAFootnote,
      resumo2FAStatus,
      resumoCodigosRecuperacao,
      twoFactorEnabled,
      twoFactorMethod,
    },
    settingsDrawerInOverview,
    settingsDrawerMatchesPage,
    settingsDrawerMatchesSection,
    settingsDrawerPage,
    settingsDrawerPageSections,
    settingsDrawerPanHandlers: settingsDrawerPanResponder.panHandlers,
    settingsDrawerSectionMenuAtiva,
    settingsDrawerSubtitle,
    settingsDrawerTitle,
    settingsPrintDarkMode,
    supportSectionProps: {
      onCanalSuporte: supportChannelLabel === "Canal indisponível" ? undefined : handleAbrirCanalSuporte,
      onCentralAjuda: handleCentralAjuda,
      onEnviarFeedback: handleEnviarFeedback,
      onExportarDiagnosticoApp: handleExportarDiagnosticoApp,
      onLicencas: handleLicencas,
      onLimparFilaSuporteLocal: handleLimparFilaSuporteLocal,
      onPoliticaPrivacidade: handlePoliticaPrivacidade,
      onReportarProblema: handleReportarProblema,
      onSobreApp: handleAbrirSobreApp,
      onTermosUso: handleTermosUso,
      resumoFilaSuporteLocal,
      resumoSuporteApp,
      supportChannelLabel,
      ticketsBugTotal,
      ticketsFeedbackTotal,
      ultimoTicketSuporte: ultimoTicketSuporteResumo,
    },
    systemSectionProps: {
      appBuildChannel: input.appBuildChannel,
      appVersionLabel: input.appVersionLabel,
      economiaDados,
      idiomaApp,
      onAbrirCentralAtividade: handleAbrirCentralAtividade,
      onFecharConfiguracoes: fecharConfiguracoes,
      onLimparCache: handleLimparCache,
      onPermissoes: handlePermissoes,
      onRefreshData: handleRefresh,
      onSetEconomiaDados: setEconomiaDados,
      onSetIdiomaApp: setIdiomaApp,
      onSetRegiaoApp: setRegiaoApp,
      onSetUsoBateria: setUsoBateria,
      onVerificarAtualizacoes: handleVerificarAtualizacoes,
      regiaoApp,
      resumoCache,
      resumoCentralAtividade,
      resumoFilaOffline: input.resumoFilaOffline,
      resumoPermissoes,
      sincronizandoDados,
      ultimaVerificacaoAtualizacaoLabel,
      usoBateria,
      verificandoAtualizacoes,
    },
    totalSecoesConfiguracaoVisiveis,
  });
}
