import { buildSettingsDrawerPanelProps } from "./buildSettingsDrawerPanelProps";

type BuildInspectorSettingsDrawerPanelPropsInput = Record<string, any>;

export function buildInspectorSettingsDrawerPanelProps(
  input: BuildInspectorSettingsDrawerPanelPropsInput,
): ReturnType<typeof buildSettingsDrawerPanelProps> {
  const {
    accountSectionContentProps,
    advancedResourcesSectionProps,
    aprendizadoIa,
    animacoesAtivas,
    arquivosPermitidos,
    artigosAjudaFiltrados,
    backupAutomatico,
    biometriaPermitida,
    cameraPermitida,
    cartaoAtual,
    codigo2FA,
    codigosRecuperacao,
    compartilharMelhoriaIa,
    configuracoesDrawerX,
    contaEmailLabel,
    contaTelefoneLabel,
    conversasOcultasTotal,
    conversasVisiveisTotal,
    corDestaque,
    corDestaqueResumoConfiguracao,
    densidadeInterface,
    deviceBiometricsEnabled,
    economiaDados,
    email,
    emailAtualConta,
    emailsAtivos,
    entradaPorVoz,
    estiloResposta,
    experienceNotificationsSectionProps,
    eventosSegurancaFiltrados,
    existeProvedorDisponivel,
    fecharConfiguracoes,
    filaSuporteLocal,
    filtroEventosSeguranca,
    fixarConversas,
    handleAbrirAjustesDoSistema,
    handleAbrirCentralAtividade,
    handleAbrirPaginaConfiguracoes,
    handleAbrirSecaoConfiguracoes,
    handleAlterarEmail,
    handleAlterarSenha,
    handleApagarHistoricoConfiguracoes,
    handleCentralAjuda,
    handleCompartilharCodigosRecuperacao,
    handleConectarProximoProvedorDisponivel,
    handleConfirmarCodigo2FA,
    handleDetalhesSegurancaArquivos,
    handleEncerrarOutrasSessoes,
    handleEncerrarSessao,
    handleEncerrarSessaoAtual,
    handleEncerrarSessoesSuspeitas,
    handleEnviarFeedback,
    handleExcluirConta,
    handleExportarAntesDeExcluirConta,
    handleExportarDados,
    handleExportarDiagnosticoApp,
    handleGerarCodigosRecuperacao,
    handleGerenciarConversasIndividuais,
    handleGerenciarPagamento,
    handleGerenciarPermissao,
    handleGerenciarPlano,
    handleHistoricoPagamentos,
    handleIntegracoesExternas,
    handleLicencas,
    handleLimparFilaSuporteLocal,
    handleLimparTodasConversasConfig,
    handleLogout,
    handleAbrirModeloIa,
    handleMudarMetodo2FA,
    handlePermissoes,
    handlePluginsIa,
    handlePoliticaPrivacidade,
    handleReautenticacaoSensivel,
    handleRefresh,
    handleReportarAtividadeSuspeita,
    handleReportarProblema,
    handleRevisarPermissoesCriticas,
    handleRevisarSessao,
    handleTermosUso,
    handleToggle2FA,
    handleToggleBackupAutomatico,
    handleToggleBiometriaNoDispositivo,
    handleToggleEntradaPorVoz,
    handleToggleMostrarConteudoNotificacao,
    handleToggleMostrarSomenteNovaMensagem,
    handleToggleNotificaPush,
    handleToggleOcultarConteudoBloqueado,
    handleToggleProviderConnection,
    handleToggleRespostaPorVoz,
    handleToggleSincronizacaoDispositivos,
    handleToggleUploadArquivos,
    handleToggleVibracao,
    handleUploadFotoPerfil,
    handleVerificarAtualizacoes,
    handleVoltarResumoConfiguracoes,
    hideInMultitask,
    idiomaApp,
    idiomaResposta,
    iniciaisPerfilConfiguracao,
    integracoesConectadasTotal,
    integracoesDisponiveisTotal,
    lockTimeout,
    memoriaIa,
    microfonePermitido,
    modeloIa,
    mostrarConteudoNotificacao,
    mostrarGrupoContaAcesso,
    mostrarGrupoExperiencia,
    mostrarGrupoSeguranca,
    mostrarGrupoSistema,
    mostrarSomenteNovaMensagem,
    nomeAutomaticoConversas,
    nomeUsuarioExibicao,
    notificaPush,
    notificaRespostas,
    notificacoesPermitidas,
    ocultarConteudoBloqueado,
    onAbrirFilaOffline,
    outrasSessoesAtivas,
    perfilExibicao,
    perfilExibicaoLabel,
    perfilFotoHint,
    perfilFotoUri,
    perfilNome,
    perfilNomeCompleto,
    permissoesNegadasTotal,
    planoAtual,
    planoResumoConfiguracao,
    previewPrivacidadeNotificacao,
    provedoresConectados,
    provedoresConectadosTotal,
    provedorPrimario,
    reautenticacaoStatus,
    recoveryCodesEnabled,
    regiaoApp,
    requireAuthOnOpen,
    respostaPorVoz,
    resumo2FAFootnote,
    resumo2FAStatus,
    resumoAlertaMetodosConta,
    resumoBlindagemSessoes,
    resumoCodigosRecuperacao,
    resumoDadosConversas,
    resumoExcluirConta,
    resumoFilaSuporteLocal,
    resumoMetodosConta,
    resumoPermissoes,
    resumoPermissoesCriticas,
    resumoPrivacidadeNotificacoes,
    resumoSessaoAtual,
    resumoSuporteApp,
    retencaoDados,
    salvarHistoricoConversas,
    setAnimacoesAtivas,
    setAprendizadoIa,
    setCodigo2FA,
    setCompartilharMelhoriaIa,
    setCorDestaque,
    setDensidadeInterface,
    setEconomiaDados,
    setEmailsAtivos,
    setEstiloResposta,
    setFiltroEventosSeguranca,
    setFixarConversas,
    setHideInMultitask,
    setIdiomaApp,
    setIdiomaResposta,
    setLockTimeout,
    setMemoriaIa,
    setNomeAutomaticoConversas,
    setNotificaRespostas,
    setPerfilExibicao,
    setPerfilNome,
    setRecoveryCodesEnabled,
    setRegiaoApp,
    setRequireAuthOnOpen,
    setRetencaoDados,
    setSalvarHistoricoConversas,
    setSomNotificacao,
    setTamanhoFonte,
    setTemperaturaIa,
    setTemaApp,
    setTomConversa,
    setUsoBateria,
    settingsDrawerInOverview,
    settingsDrawerMatchesPage,
    settingsDrawerMatchesSection,
    settingsDrawerPage,
    settingsDrawerPageSections,
    settingsDrawerPanResponder,
    settingsDrawerSectionMenuAtiva,
    settingsDrawerSubtitle,
    settingsDrawerTitle,
    settingsPrintDarkMode,
    sessoesAtivas,
    sessoesSuspeitasTotal,
    sincronizacaoDispositivos,
    somNotificacao,
    tamanhoFonte,
    temperaturaIa,
    temaApp,
    temaResumoConfiguracao,
    temPrioridadesConfiguracao,
    ticketsBugTotal,
    ticketsFeedbackTotal,
    tomConversa,
    totalSecoesConfiguracaoVisiveis,
    twoFactorEnabled,
    twoFactorMethod,
    ultimaVerificacaoAtualizacaoLabel,
    ultimoEventoProvedor,
    ultimoEventoSessao,
    ultimoTicketSuporteResumo,
    uploadArquivosAtivo,
    usoBateria,
    vibracaoAtiva,
    workspaceResumoConfiguracao,
  } = input;

  return buildSettingsDrawerPanelProps({
    accountSectionContentProps: accountSectionContentProps || {
      cartaoAtual,
      contaEmailLabel,
      onAlterarEmail: handleAlterarEmail,
      onAlterarSenha: handleAlterarSenha,
      onExcluirConta: handleExcluirConta,
      onFecharConfiguracoes: fecharConfiguracoes,
      onGerenciarPagamento: handleGerenciarPagamento,
      onGerenciarPlano: handleGerenciarPlano,
      onHistoricoPagamentos: handleHistoricoPagamentos,
      onLogout: handleLogout,
      onSetPerfilExibicao: setPerfilExibicao,
      onSetPerfilNome: setPerfilNome,
      onUploadFotoPerfil: handleUploadFotoPerfil,
      perfilExibicao,
      perfilExibicaoLabel,
      perfilFotoHint,
      perfilFotoUri,
      perfilNome,
      perfilNomeCompleto,
      planoAtual,
      provedorPrimario,
      reautenticacaoStatus,
      resumoMetodosConta,
    },
    advancedResourcesSectionProps: advancedResourcesSectionProps || {
      entradaPorVoz,
      integracoesConectadasTotal,
      integracoesDisponiveisTotal,
      onIntegracoesExternas: handleIntegracoesExternas,
      onPluginsIa: handlePluginsIa,
      onToggleEntradaPorVoz: handleToggleEntradaPorVoz,
      onToggleRespostaPorVoz: handleToggleRespostaPorVoz,
      onToggleUploadArquivos: handleToggleUploadArquivos,
      respostaPorVoz,
      uploadArquivosAtivo,
    },
    artigosAjudaCount: artigosAjudaFiltrados.length,
    configuracoesDrawerX,
    emailRetorno: emailAtualConta || email || "Defina um email na conta",
    experienceAiSectionProps: {
      aprendizadoIa,
      estiloResposta,
      idiomaResposta,
      memoriaIa,
      modeloIa,
      onAbrirMenuModeloIa: handleAbrirModeloIa,
      onSetAprendizadoIa: setAprendizadoIa,
      onSetEstiloResposta: setEstiloResposta,
      onSetIdiomaResposta: setIdiomaResposta,
      onSetMemoriaIa: setMemoriaIa,
      onSetTemperaturaIa: setTemperaturaIa,
      onSetTomConversa: setTomConversa,
      temperaturaIa,
      tomConversa,
    },
    experienceAppearanceSectionProps: {
      animacoesAtivas,
      corDestaque,
      densidadeInterface,
      onSetAnimacoesAtivas: setAnimacoesAtivas,
      onSetCorDestaque: setCorDestaque,
      onSetDensidadeInterface: setDensidadeInterface,
      onSetTamanhoFonte: setTamanhoFonte,
      onSetTemaApp: setTemaApp,
      tamanhoFonte,
      temaApp,
    },
    experienceNotificationsSectionProps: experienceNotificationsSectionProps || {
      emailsAtivos,
      notificaPush,
      notificaRespostas,
      onSetEmailsAtivos: setEmailsAtivos,
      onSetNotificaRespostas: setNotificaRespostas,
      onSetSomNotificacao: setSomNotificacao,
      onToggleNotificaPush: handleToggleNotificaPush,
      onToggleVibracao: handleToggleVibracao,
      somNotificacao,
      vibracaoAtiva,
    },
    fecharConfiguracoes,
    filaSuporteCount: filaSuporteLocal.length,
    handleVoltarResumoConfiguracoes,
    mostrarGrupoContaAcesso,
    mostrarGrupoExperiencia,
    mostrarGrupoSeguranca,
    mostrarGrupoSistema,
    onAbrirFilaOffline,
    overviewContentProps: {
      contaEmailLabel,
      contaTelefoneLabel,
      corDestaqueResumoConfiguracao,
      iniciaisPerfilConfiguracao,
      nomeUsuarioExibicao,
      onAbrirPaginaConfiguracoes: handleAbrirPaginaConfiguracoes,
      onFecharConfiguracoes: fecharConfiguracoes,
      onLogout: handleLogout,
      onReportarProblema: handleReportarProblema,
      onUploadFotoPerfil: handleUploadFotoPerfil,
      perfilFotoUri,
      planoResumoConfiguracao,
      settingsPrintDarkMode,
      temaResumoConfiguracao,
      workspaceResumoConfiguracao,
    },
    priorityActionsContentProps: {
      existeProvedorDisponivel,
      onConectarProximoProvedorDisponivel: handleConectarProximoProvedorDisponivel,
      onEncerrarSessoesSuspeitas: handleEncerrarSessoesSuspeitas,
      onRevisarPermissoesCriticas: handleRevisarPermissoesCriticas,
      onToggle2FA: handleToggle2FA,
      onVerificarAtualizacoes: handleVerificarAtualizacoes,
      permissoesNegadasTotal,
      provedoresConectadosTotal,
      sessoesSuspeitasTotal,
      temPrioridadesConfiguracao,
      twoFactorEnabled,
      ultimaVerificacaoAtualizacaoLabel,
    },
    sectionMenuContentProps: {
      onAbrirSecaoConfiguracoes: handleAbrirSecaoConfiguracoes,
    },
    securityActivitySectionProps: {
      eventosSegurancaFiltrados,
      filtroEventosSeguranca,
      onReportarAtividadeSuspeita: handleReportarAtividadeSuspeita,
      onSetFiltroEventosSeguranca: setFiltroEventosSeguranca,
    },
    securityConnectedAccountsSectionProps: {
      onToggleProviderConnection: handleToggleProviderConnection,
      provedoresConectados,
      provedoresConectadosTotal,
      provedorPrimario,
      resumoAlertaMetodosConta,
      ultimoEventoProvedor,
    },
    securityDataConversationsSectionProps: {
      backupAutomatico,
      compartilharMelhoriaIa,
      conversasOcultasTotal,
      conversasVisiveisTotal,
      fixarConversas,
      nomeAutomaticoConversas,
      onApagarHistoricoConfiguracoes: handleApagarHistoricoConfiguracoes,
      onExportarDados: handleExportarDados,
      onGerenciarConversasIndividuais: handleGerenciarConversasIndividuais,
      onLimparTodasConversasConfig: handleLimparTodasConversasConfig,
      onSetCompartilharMelhoriaIa: setCompartilharMelhoriaIa,
      onSetFixarConversas: setFixarConversas,
      onSetNomeAutomaticoConversas: setNomeAutomaticoConversas,
      onSetRetencaoDados: setRetencaoDados,
      onSetSalvarHistoricoConversas: setSalvarHistoricoConversas,
      onToggleBackupAutomatico: handleToggleBackupAutomatico,
      onToggleSincronizacaoDispositivos: handleToggleSincronizacaoDispositivos,
      retencaoDados,
      resumoDadosConversas,
      salvarHistoricoConversas,
      sincronizacaoDispositivos,
    },
    securityDeleteAccountSectionProps: {
      onExcluirConta: handleExcluirConta,
      onExportarAntesDeExcluirConta: handleExportarAntesDeExcluirConta,
      onReautenticacaoSensivel: handleReautenticacaoSensivel,
      reautenticacaoStatus,
      resumoExcluirConta,
    },
    securityDeviceProtectionSectionProps: {
      deviceBiometricsEnabled,
      hideInMultitask,
      lockTimeout,
      onSetHideInMultitask: setHideInMultitask,
      onSetLockTimeout: setLockTimeout,
      onSetRequireAuthOnOpen: setRequireAuthOnOpen,
      onToggleBiometriaNoDispositivo: handleToggleBiometriaNoDispositivo,
      requireAuthOnOpen,
    },
    securityFileUploadSectionProps: {
      onDetalhesSegurancaArquivos: handleDetalhesSegurancaArquivos,
    },
    securityIdentityVerificationSectionProps: {
      onReautenticacaoSensivel: handleReautenticacaoSensivel,
      reautenticacaoStatus,
    },
    securityNotificationPrivacySectionProps: {
      mostrarConteudoNotificacao,
      mostrarSomenteNovaMensagem,
      ocultarConteudoBloqueado,
      onToggleMostrarConteudoNotificacao: handleToggleMostrarConteudoNotificacao,
      onToggleMostrarSomenteNovaMensagem: handleToggleMostrarSomenteNovaMensagem,
      onToggleOcultarConteudoBloqueado: handleToggleOcultarConteudoBloqueado,
      previewPrivacidadeNotificacao,
      resumoPrivacidadeNotificacoes,
    },
    securityPermissionsSectionProps: {
      arquivosPermitidos,
      biometriaPermitida,
      cameraPermitida,
      microfonePermitido,
      notificacoesPermitidas,
      onAbrirAjustesDoSistema: handleAbrirAjustesDoSistema,
      onGerenciarPermissao: handleGerenciarPermissao,
      onRevisarPermissoesCriticas: handleRevisarPermissoesCriticas,
      permissoesNegadasTotal,
      resumoPermissoes,
      resumoPermissoesCriticas,
    },
    securitySessionsSectionProps: {
      onEncerrarOutrasSessoes: handleEncerrarOutrasSessoes,
      onEncerrarSessao: handleEncerrarSessao,
      onEncerrarSessaoAtual: handleEncerrarSessaoAtual,
      onEncerrarSessoesSuspeitas: handleEncerrarSessoesSuspeitas,
      onFecharConfiguracoes: fecharConfiguracoes,
      onLogout: handleLogout,
      onRevisarSessao: handleRevisarSessao,
      outrasSessoesAtivas,
      resumoBlindagemSessoes,
      resumoSessaoAtual,
      sessoesAtivas,
      sessoesSuspeitasTotal,
      ultimoEventoSessao,
    },
    securityTwoFactorSectionProps: {
      codigo2FA,
      codigosRecuperacao,
      onCompartilharCodigosRecuperacao: handleCompartilharCodigosRecuperacao,
      onConfirmarCodigo2FA: handleConfirmarCodigo2FA,
      onGerarCodigosRecuperacao: handleGerarCodigosRecuperacao,
      onMudarMetodo2FA: handleMudarMetodo2FA,
      onSetCodigo2FA: setCodigo2FA,
      onSetRecoveryCodesEnabled: setRecoveryCodesEnabled,
      onToggle2FA: handleToggle2FA,
      reautenticacaoStatus,
      recoveryCodesEnabled,
      resumo2FAFootnote,
      resumo2FAStatus,
      resumoCodigosRecuperacao,
      twoFactorEnabled,
      twoFactorMethod,
    },
    settingsDrawerInOverview,
    settingsDrawerMatchesPage,
    settingsDrawerMatchesSection,
    settingsDrawerPage,
    settingsDrawerPageSections,
    settingsDrawerPanHandlers: settingsDrawerPanResponder.panHandlers,
    settingsDrawerSectionMenuAtiva,
    settingsDrawerSubtitle,
    settingsDrawerTitle,
    settingsPrintDarkMode,
    supportSectionProps: {
      onCentralAjuda: handleCentralAjuda,
      onEnviarFeedback: handleEnviarFeedback,
      onExportarDiagnosticoApp: handleExportarDiagnosticoApp,
      onLicencas: handleLicencas,
      onLimparFilaSuporteLocal: handleLimparFilaSuporteLocal,
      onPoliticaPrivacidade: handlePoliticaPrivacidade,
      onReportarProblema: handleReportarProblema,
      onTermosUso: handleTermosUso,
      resumoFilaSuporteLocal,
      resumoSuporteApp,
      ticketsBugTotal,
      ticketsFeedbackTotal,
      ultimoTicketSuporte: ultimoTicketSuporteResumo,
    },
    systemSectionProps: {
      economiaDados,
      idiomaApp,
      onAbrirCentralAtividade: handleAbrirCentralAtividade,
      onFecharConfiguracoes: fecharConfiguracoes,
      onPermissoes: handlePermissoes,
      onRefreshData: handleRefresh,
      onSetEconomiaDados: setEconomiaDados,
      onSetIdiomaApp: setIdiomaApp,
      onSetRegiaoApp: setRegiaoApp,
      onSetUsoBateria: setUsoBateria,
      onVerificarAtualizacoes: handleVerificarAtualizacoes,
      regiaoApp,
      resumoPermissoes,
      ultimaVerificacaoAtualizacaoLabel,
      usoBateria,
    },
    totalSecoesConfiguracaoVisiveis,
  });
}
