import { StyleSheet } from "react-native";

import { colors, radii, spacing } from "../theme/tokens";
import { chatStyles } from "./styles/chatStyles";
import { historyStyles } from "./styles/historyStyles";
import { loginStyles } from "./styles/loginStyles";
import { settingsSecurityStyles } from "./styles/settingsSecurityStyles";

export const styles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  launchOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 40,
  },
  launchOverlayGradient: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  launchOverlayInner: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
  },
  launchOverlayHalo: {
    position: "absolute",
    width: 156,
    height: 156,
    borderRadius: 78,
    backgroundColor: "rgba(244,123,32,0.08)",
  },
  launchOverlayMark: {
    width: 108,
    height: 108,
    borderRadius: 32,
    shadowColor: colors.ink900,
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 6,
  },
  launchOverlayBrand: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: "800",
    letterSpacing: 3,
    textTransform: "uppercase",
  },
  launchOverlaySubtitle: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  safeArea: {
    flex: 1,
  },
  keyboard: {
    flex: 1,
  },
  scrollContent: {
    padding: spacing.lg,
    gap: spacing.lg,
  },
  ...loginStyles,
  heroCard: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: radii.lg,
    padding: spacing.xl,
    gap: spacing.md,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  brandRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.md,
  },
  brandEyebrow: {
    color: colors.accentSoft,
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  brandTitle: {
    color: colors.white,
    fontSize: 28,
    fontWeight: "800",
    marginTop: 4,
  },
  heroTitle: {
    color: colors.white,
    fontSize: 28,
    fontWeight: "800",
    lineHeight: 34,
  },
  heroDescription: {
    color: "rgba(238,243,247,0.8)",
    fontSize: 15,
    lineHeight: 22,
  },
  heroTags: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  heroTag: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  heroTagLabel: {
    color: colors.white,
    fontWeight: "700",
  },
  serverCard: {
    marginTop: spacing.sm,
    backgroundColor: "rgba(9,16,25,0.35)",
    borderRadius: radii.md,
    padding: spacing.md,
    gap: spacing.xs,
  },
  serverLabel: {
    color: colors.accentSoft,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1.1,
    fontWeight: "700",
  },
  serverValue: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "600",
  },
  secondaryButton: {
    alignSelf: "flex-start",
    marginTop: spacing.sm,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  secondaryButtonText: {
    color: colors.white,
    fontWeight: "700",
  },
  formCard: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: radii.lg,
    padding: spacing.xl,
    gap: spacing.md,
    shadowColor: colors.ink900,
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  loadingState: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.md,
    paddingVertical: spacing.xxl,
  },
  loadingText: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  dashboardState: {
    gap: spacing.md,
  },
  formEyebrow: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.1,
  },
  formTitle: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: "800",
  },
  formDescription: {
    color: colors.textSecondary,
    fontSize: 15,
    lineHeight: 22,
  },
  inputGroup: {
    gap: spacing.xs,
  },
  label: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  input: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    color: colors.textPrimary,
    fontSize: 15,
  },
  passwordWrapper: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.white,
  },
  passwordInput: {
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    color: colors.textPrimary,
    fontSize: 15,
  },
  passwordToggle: {
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
  },
  switchRow: {
    marginTop: spacing.xs,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  switchLabel: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  switchHint: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: 4,
    maxWidth: 240,
  },
  errorText: {
    color: colors.danger,
    fontSize: 14,
    fontWeight: "600",
  },
  primaryButton: {
    marginTop: spacing.sm,
    borderRadius: radii.md,
    backgroundColor: colors.accent,
    minHeight: 54,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonDisabled: {
    opacity: 0.75,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "800",
  },
  footerHint: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 20,
  },
  ...chatStyles,
  ...settingsSecurityStyles,
  ...historyStyles,
  metricsRow: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  metricCard: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: radii.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    gap: 6,
  },
  metricValue: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: "800",
  },
  metricLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  actionList: {
    gap: spacing.sm,
  },
  actionItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    backgroundColor: colors.white,
    borderRadius: radii.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  actionText: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
});
