import { StyleSheet } from "react-native";

import { colors, radii, spacing } from "../theme/tokens";
import {
  PANEL_EDGE_GESTURE_TOP_OFFSET,
  PANEL_EDGE_GESTURE_WIDTH,
  SIDE_PANEL_WIDTH,
} from "./InspectorMobileApp.constants";

export const styles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  launchOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 40,
  },
  launchOverlayGradient: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  launchOverlayInner: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
  },
  launchOverlayHalo: {
    position: "absolute",
    width: 156,
    height: 156,
    borderRadius: 78,
    backgroundColor: "rgba(244,123,32,0.08)",
  },
  launchOverlayMark: {
    width: 108,
    height: 108,
    borderRadius: 32,
    shadowColor: colors.ink900,
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 6,
  },
  launchOverlayBrand: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: "800",
    letterSpacing: 3,
    textTransform: "uppercase",
  },
  launchOverlaySubtitle: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  safeArea: {
    flex: 1,
  },
  keyboard: {
    flex: 1,
  },
  scrollContent: {
    padding: spacing.lg,
    gap: spacing.lg,
  },
  loginScrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xxl,
  },
  loginScrollContentKeyboardVisible: {
    justifyContent: "flex-start",
    paddingTop: spacing.xl,
    paddingBottom: spacing.xl,
  },
  loginScreen: {
    gap: spacing.xl,
  },
  loginBrand: {
    alignItems: "center",
    gap: spacing.sm,
    paddingBottom: spacing.sm,
  },
  brandStageCompact: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
  },
  brandHaloCompact: {
    position: "absolute",
    top: -10,
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: "rgba(244,123,32,0.06)",
  },
  brandMarkCompact: {
    width: 92,
    height: 92,
    borderRadius: 28,
    shadowColor: colors.ink900,
    shadowOpacity: 0.14,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  brandLabelCompact: {
    color: colors.textSecondary,
    fontSize: 16,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 2.4,
  },
  loginCard: {
    backgroundColor: "#FFFDFC",
    borderRadius: 32,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
    paddingBottom: spacing.xxl,
    gap: spacing.lg,
    borderWidth: 1,
    borderColor: "rgba(231,216,200,0.96)",
    shadowColor: colors.ink900,
    shadowOpacity: 0.08,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 8,
  },
  loginFields: {
    gap: spacing.md,
  },
  mobileField: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: "#FFFCF8",
    paddingHorizontal: spacing.md,
  },
  mobileFieldInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 17,
    paddingVertical: 16,
  },
  mobileFieldAction: {
    width: 32,
    height: 32,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
  },
  loginForgotRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  loginMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  loginRememberRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  loginCheckbox: {
    width: 18,
    height: 18,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#CAD6E2",
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  loginCheckboxActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  loginRememberText: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  loginForgotLink: {
    color: colors.ink600,
    fontSize: 13,
    fontWeight: "700",
  },
  loginPrimaryButton: {
    minHeight: 58,
    borderRadius: 20,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.accent,
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  loginPrimaryButtonText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: "800",
  },
  loginDividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  loginDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#E5ECF3",
  },
  loginDividerText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "600",
  },
  loginSocialStack: {
    gap: spacing.sm,
  },
  loginSocialLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  loginSocialButton: {
    minHeight: 50,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: "#FFFDFC",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  loginSocialIconShell: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  loginSocialButtonText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  loginFooterText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  heroCard: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: radii.lg,
    padding: spacing.xl,
    gap: spacing.md,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  brandRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.md,
  },
  brandEyebrow: {
    color: colors.accentSoft,
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  brandTitle: {
    color: colors.white,
    fontSize: 28,
    fontWeight: "800",
    marginTop: 4,
  },
  heroTitle: {
    color: colors.white,
    fontSize: 28,
    fontWeight: "800",
    lineHeight: 34,
  },
  heroDescription: {
    color: "rgba(238,243,247,0.8)",
    fontSize: 15,
    lineHeight: 22,
  },
  heroTags: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  heroTag: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  heroTagLabel: {
    color: colors.white,
    fontWeight: "700",
  },
  serverCard: {
    marginTop: spacing.sm,
    backgroundColor: "rgba(9,16,25,0.35)",
    borderRadius: radii.md,
    padding: spacing.md,
    gap: spacing.xs,
  },
  serverLabel: {
    color: colors.accentSoft,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1.1,
    fontWeight: "700",
  },
  serverValue: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "600",
  },
  secondaryButton: {
    alignSelf: "flex-start",
    marginTop: spacing.sm,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  secondaryButtonText: {
    color: colors.white,
    fontWeight: "700",
  },
  formCard: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: radii.lg,
    padding: spacing.xl,
    gap: spacing.md,
    shadowColor: colors.ink900,
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  loadingState: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.md,
    paddingVertical: spacing.xxl,
  },
  loadingText: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  dashboardState: {
    gap: spacing.md,
  },
  formEyebrow: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.1,
  },
  formTitle: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: "800",
  },
  formDescription: {
    color: colors.textSecondary,
    fontSize: 15,
    lineHeight: 22,
  },
  inputGroup: {
    gap: spacing.xs,
  },
  label: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  input: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    color: colors.textPrimary,
    fontSize: 15,
  },
  passwordWrapper: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.white,
  },
  passwordInput: {
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    color: colors.textPrimary,
    fontSize: 15,
  },
  passwordToggle: {
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
  },
  switchRow: {
    marginTop: spacing.xs,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  switchLabel: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  switchHint: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: 4,
    maxWidth: 240,
  },
  errorText: {
    color: colors.danger,
    fontSize: 14,
    fontWeight: "600",
  },
  primaryButton: {
    marginTop: spacing.sm,
    borderRadius: radii.md,
    backgroundColor: colors.accent,
    minHeight: 54,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonDisabled: {
    opacity: 0.75,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "800",
  },
  footerHint: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 20,
  },
  chatLayout: {
    flex: 1,
  },
  chatHeader: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    gap: spacing.md,
  },
  cleanHeaderTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  cleanHeaderSpacer: {
    flex: 1,
  },
  cleanNavButton: {
    width: 42,
    height: 42,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFBF6",
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    position: "relative",
  },
  cleanHeaderCopy: {
    flex: 1,
    alignItems: "center",
    gap: 2,
  },
  cleanHeaderEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1.1,
  },
  cleanHeaderTitle: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: "800",
  },
  cleanHeaderSubtitle: {
    color: colors.textSecondary,
    fontSize: 12,
    textAlign: "center",
    maxWidth: 220,
  },
  cleanHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  cleanNavBadge: {
    position: "absolute",
    top: -3,
    right: -2,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: radii.pill,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  cleanNavBadgeText: {
    color: colors.white,
    fontSize: 10,
    fontWeight: "800",
  },
  cleanHeaderStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cleanReopenAction: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: "#FFF8F1",
    borderWidth: 1,
    borderColor: "#F1D7C0",
  },
  cleanReopenActionText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "700",
  },
  cleanHeaderChipRail: {
    gap: spacing.xs,
    paddingRight: spacing.sm,
  },
  cleanHeaderChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 9,
    borderRadius: radii.pill,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  cleanHeaderChipAccent: {
    backgroundColor: "#FFF3E7",
    borderColor: "#FFD6B2",
  },
  cleanHeaderChipText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
    maxWidth: 220,
  },
  cleanHeaderChipTextAccent: {
    color: colors.accent,
  },
  chatHeaderTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  chatHeaderIdentity: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    flex: 1,
  },
  userBadge: {
    width: 46,
    height: 46,
    borderRadius: radii.pill,
    backgroundColor: "rgba(244,123,32,0.18)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  userBadgeText: {
    color: colors.accentSoft,
    fontSize: 18,
    fontWeight: "800",
  },
  chatHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  chatEyebrow: {
    color: colors.accentSoft,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  chatTitle: {
    color: colors.white,
    fontSize: 24,
    fontWeight: "800",
  },
  chatSubtitle: {
    color: "rgba(238,243,247,0.74)",
    fontSize: 13,
  },
  chatHeaderActions: {
    alignItems: "flex-end",
    gap: spacing.sm,
  },
  chatHeaderActionRail: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: radii.pill,
    paddingHorizontal: 6,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  chatHeaderMetaRail: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  chatHeaderMetaChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  chatHeaderMetaText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "700",
    maxWidth: 180,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  iconButtonBadge: {
    position: "absolute",
    top: -3,
    right: -3,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: radii.pill,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  iconButtonBadgeText: {
    color: colors.white,
    fontSize: 10,
    fontWeight: "800",
  },
  chatPanel: {
    flex: 1,
    backgroundColor: "transparent",
    paddingTop: spacing.sm,
    paddingHorizontal: spacing.lg,
    gap: spacing.md,
  },
  chatPanelKeyboardVisible: {
    paddingTop: spacing.xs,
    gap: spacing.sm,
  },
  threadHeaderCard: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: radii.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    borderTopColor: "#F0B98B",
    borderTopWidth: 1.5,
    gap: spacing.sm,
  },
  threadHeaderTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.md,
  },
  threadHeaderCopy: {
    flex: 1,
  },
  threadSpotlightBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  threadSpotlightBadgeAccent: {
    backgroundColor: "#FFF1E4",
    borderColor: "#FFD6B2",
  },
  threadSpotlightBadgeSuccess: {
    backgroundColor: "#EEF9F3",
    borderColor: "#BCE8D0",
  },
  threadSpotlightText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  threadSpotlightTextAccent: {
    color: colors.accent,
  },
  threadSpotlightTextSuccess: {
    color: colors.success,
  },
  threadEyebrow: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  threadTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "800",
    marginTop: 2,
  },
  threadDescription: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  threadContextChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  threadContextChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  threadContextChipAccent: {
    backgroundColor: "#FFF1E4",
    borderColor: "#FFD6B2",
  },
  threadContextChipSuccess: {
    backgroundColor: "#EEF9F3",
    borderColor: "#BCE8D0",
  },
  threadContextChipDanger: {
    backgroundColor: "#FDEEEE",
    borderColor: "#F6CACA",
  },
  threadContextChipText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    maxWidth: 220,
  },
  threadContextChipTextAccent: {
    color: colors.accent,
  },
  threadContextChipTextSuccess: {
    color: colors.success,
  },
  threadContextChipTextDanger: {
    color: colors.danger,
  },
  threadInsightGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  threadInsightCard: {
    width: "48%",
    minWidth: 148,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    padding: spacing.sm,
    borderRadius: radii.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  threadInsightCardAccent: {
    backgroundColor: "#FFF8F1",
    borderColor: "#FFD6B2",
  },
  threadInsightCardSuccess: {
    backgroundColor: "#EEF9F3",
    borderColor: "#BCE8D0",
  },
  threadInsightCardDanger: {
    backgroundColor: "#FDEEEE",
    borderColor: "#F6CACA",
  },
  threadInsightIcon: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  threadInsightIconAccent: {
    backgroundColor: "#FFF1E4",
  },
  threadInsightIconSuccess: {
    backgroundColor: "#DDF5E8",
  },
  threadInsightIconDanger: {
    backgroundColor: "#FCE1E1",
  },
  threadInsightCopy: {
    flex: 1,
    gap: 2,
  },
  threadInsightLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  threadInsightValue: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  threadInsightDetail: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  threadTabs: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  cleanTabShell: {
    borderRadius: 20,
    backgroundColor: "#FFF6EE",
    padding: 6,
    borderWidth: 1,
    borderColor: "#E9D7C4",
    shadowColor: colors.ink900,
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  threadTabsShell: {
    backgroundColor: colors.white,
    borderRadius: radii.md,
    padding: 6,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  threadTab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    backgroundColor: "#FFFDFC",
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: "#E9D9C8",
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
  },
  threadTabActive: {
    backgroundColor: colors.ink800,
    borderColor: colors.ink800,
  },
  threadTabText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "700",
  },
  threadTabTextActive: {
    color: colors.white,
  },
  threadTabBadge: {
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: radii.pill,
    backgroundColor: "#FFF1E4",
    alignItems: "center",
    justifyContent: "center",
  },
  threadTabBadgeActive: {
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  threadTabBadgeText: {
    color: colors.accent,
    fontSize: 10,
    fontWeight: "800",
  },
  threadTabBadgeTextActive: {
    color: colors.white,
  },
  threadMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  threadMetaText: {
    color: colors.textSecondary,
    fontSize: 12,
    flex: 1,
  },
  laudosSection: {
    gap: spacing.sm,
  },
  laudosSectionCopy: {
    flex: 1,
    gap: 2,
  },
  laudosSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  laudosSectionEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  laudosSectionTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  laudosRail: {
    gap: spacing.sm,
    paddingRight: spacing.sm,
  },
  laudoChip: {
    width: 196,
    backgroundColor: colors.white,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    padding: spacing.md,
    gap: spacing.xs,
  },
  laudoChipTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  laudoChipEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  laudoChipEyebrowActive: {
    color: colors.accentSoft,
  },
  laudoChipActive: {
    backgroundColor: colors.ink800,
    borderColor: colors.ink800,
  },
  laudoChipTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  laudoChipTitleActive: {
    color: colors.white,
  },
  laudoChipPreview: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    minHeight: 36,
  },
  laudoChipPreviewActive: {
    color: "rgba(255,255,255,0.82)",
  },
  laudoChipMeta: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "600",
  },
  laudoChipMetaActive: {
    color: "rgba(255,255,255,0.66)",
  },
  laudoChipStatus: {
    alignSelf: "flex-start",
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    marginTop: spacing.xs,
  },
  laudoChipStatusText: {
    fontSize: 11,
    fontWeight: "700",
  },
  activityStrip: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.white,
    padding: spacing.md,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  activityStripIcon: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    backgroundColor: "rgba(244,123,32,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  activityStripCopy: {
    flex: 1,
    gap: 2,
  },
  activityStripTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  activityStripBody: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  activityStripTime: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
  },
  offlineReadBanner: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: "#FFD6B2",
    backgroundColor: "#FFF7EE",
    padding: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  offlineReadBannerIcon: {
    width: 36,
    height: 36,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  offlineReadBannerCopy: {
    flex: 1,
    gap: 2,
  },
  offlineReadBannerTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  offlineReadBannerText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  offlineQueueCard: {
    gap: spacing.sm,
    backgroundColor: "#FFF8F1",
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: "#FFD6B2",
    padding: spacing.md,
  },
  offlineQueueHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  offlineQueueActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  offlineQueueCopy: {
    flex: 1,
    gap: 2,
  },
  offlineQueueTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  offlineQueueDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  offlineQueueSummaryChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  offlineQueueSummaryChip: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radii.pill,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  offlineQueueSummaryChipAccent: {
    backgroundColor: "#FFF1E4",
    borderColor: "#FFD6B2",
  },
  offlineQueueSummaryChipDanger: {
    backgroundColor: "#FDEAEA",
    borderColor: "#F6CACA",
  },
  offlineQueueSummaryChipText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  offlineQueueSummaryChipTextAccent: {
    color: colors.accent,
  },
  offlineQueueSummaryChipTextDanger: {
    color: colors.danger,
  },
  offlineQueueSyncButton: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#FFD6B2",
  },
  offlineQueueOpenButton: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#FFD6B2",
  },
  offlineQueueSyncButtonDisabled: {
    opacity: 0.55,
  },
  offlineQueueItems: {
    gap: spacing.xs,
  },
  offlineQueueItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    backgroundColor: colors.white,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: "#FFE7CF",
    paddingHorizontal: spacing.sm,
    paddingVertical: 10,
  },
  offlineQueueItemContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  offlineQueueItemBadge: {
    width: 32,
    height: 32,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF1E4",
  },
  offlineQueueItemCopy: {
    flex: 1,
    gap: 2,
  },
  offlineQueueItemTitle: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
  },
  offlineQueueItemText: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  offlineQueueItemMeta: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  offlineQueueItemRemove: {
    width: 28,
    height: 28,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  offlineQueueFooter: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  offlineModalToolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: radii.md,
    backgroundColor: "#FFF8F1",
    borderWidth: 1,
    borderColor: "#FFE2C4",
  },
  offlineModalToolbarText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  offlineModalSyncButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#FFD6B2",
  },
  offlineModalSyncButtonDisabled: {
    opacity: 0.55,
  },
  offlineModalSyncText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "700",
  },
  offlineModalSyncTextDisabled: {
    color: colors.textSecondary,
  },
  offlineModalFilters: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  offlineModalFilterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  offlineModalFilterChipActive: {
    backgroundColor: "#FFF1E4",
    borderColor: "#FFD6B2",
  },
  offlineModalFilterText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  offlineModalFilterTextActive: {
    color: colors.accent,
  },
  offlineModalFilterCount: {
    minWidth: 24,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  offlineModalFilterCountActive: {
    backgroundColor: colors.accent,
  },
  offlineModalFilterCountText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  offlineModalFilterCountTextActive: {
    color: colors.white,
  },
  offlineModalItem: {
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: radii.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  offlineModalItemTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  offlineModalItemBadge: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF1E4",
  },
  offlineModalItemCopy: {
    flex: 1,
    gap: 4,
  },
  offlineModalItemHeading: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  offlineModalItemTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  offlineModalItemTime: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  offlineModalItemText: {
    color: colors.textPrimary,
    fontSize: 13,
    lineHeight: 19,
  },
  offlineModalItemHint: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  offlineModalItemStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    flexWrap: "wrap",
  },
  offlineModalItemStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radii.pill,
    backgroundColor: "#FFF1E4",
  },
  offlineModalItemStatusBadgeError: {
    backgroundColor: "#FDEAEA",
  },
  offlineModalItemStatusBadgeText: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
  },
  offlineModalItemStatusBadgeTextError: {
    color: colors.danger,
  },
  offlineModalItemStatusText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  offlineModalItemActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: spacing.xs,
    flexWrap: "wrap",
  },
  offlineModalActionGhost: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radii.pill,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#FFD6B2",
  },
  offlineModalActionGhostDisabled: {
    opacity: 0.55,
  },
  offlineModalActionGhostText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "700",
  },
  offlineModalActionGhostTextDisabled: {
    color: colors.textSecondary,
  },
  offlineModalActionPrimary: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radii.pill,
    backgroundColor: colors.accent,
  },
  offlineModalActionPrimaryText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "800",
  },
  offlineModalActionSecondary: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceSoft,
  },
  offlineModalActionSecondaryText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  laudoStatusBadge: {
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
  },
  laudoStatusText: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  reopenButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: "#FFF5ED",
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
  },
  reopenButtonText: {
    color: colors.accent,
    fontWeight: "700",
  },
  threadBody: {
    flex: 1,
    minHeight: 280,
    backgroundColor: "#FFFCF7",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#EADAC8",
    borderTopColor: "#F0B98B",
    borderTopWidth: 1.5,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    shadowColor: colors.ink900,
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  threadBodyKeyboardVisible: {
    minHeight: 220,
  },
  threadEmptyState: {
    minHeight: 260,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.xl,
  },
  threadEmptyBrandStage: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.md,
  },
  threadEmptyBrandHalo: {
    position: "absolute",
    top: -12,
    width: 122,
    height: 122,
    borderRadius: 61,
    backgroundColor: "rgba(244,123,32,0.08)",
  },
  threadEmptyBrandMark: {
    width: 88,
    height: 88,
    borderRadius: 28,
    shadowColor: colors.ink900,
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  threadEmptyBrand: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1.4,
    marginTop: -2,
  },
  threadEmptyTitle: {
    color: colors.textPrimary,
    fontSize: 23,
    fontWeight: "800",
    textAlign: "center",
    lineHeight: 31,
    maxWidth: 300,
  },
  threadEmptyText: {
    color: colors.textSecondary,
    fontSize: 15,
    lineHeight: 23,
    textAlign: "center",
    maxWidth: 300,
  },
  threadEmptySuggestionRail: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  threadEmptySuggestion: {
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: "#FFD9BC",
    backgroundColor: "#FFF8F1",
  },
  threadEmptySuggestionText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "700",
  },
  threadContent: {
    paddingTop: spacing.xs,
    paddingBottom: spacing.md,
    gap: spacing.md,
  },
  threadContentKeyboard: {
    paddingBottom: spacing.lg,
  },
  messageRow: {
    width: "100%",
  },
  messageRowIncoming: {
    alignItems: "flex-start",
  },
  messageRowOutgoing: {
    alignItems: "flex-end",
  },
  messageIncomingCluster: {
    maxWidth: "92%",
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 10,
  },
  messageAvatar: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    marginBottom: 6,
  },
  messageAvatarTariel: {
    backgroundColor: "#EEF5FB",
    borderColor: "#D9E6F2",
  },
  messageAvatarBrand: {
    width: 36,
    height: 36,
    borderRadius: 12,
    marginBottom: 6,
    shadowColor: colors.ink900,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  messageAvatarEngineering: {
    backgroundColor: "#FFF4E8",
    borderColor: "#EEC8A7",
  },
  messageAvatarMesa: {
    backgroundColor: "#FFF4E8",
    borderColor: "#EEC8A7",
  },
  messageBubble: {
    maxWidth: "84%",
    borderRadius: 24,
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    gap: 8,
  },
  messageBubbleIncomingShell: {
    flexShrink: 1,
    maxWidth: "100%",
  },
  messageBubbleIncoming: {
    backgroundColor: "#FFF9F3",
    borderWidth: 1,
    borderColor: "#EEDFD0",
    borderTopWidth: 1.5,
    borderTopColor: "#F5CAA0",
    borderTopLeftRadius: 18,
    borderBottomLeftRadius: 10,
    shadowColor: colors.ink900,
    shadowOpacity: 0.035,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 2,
  },
  messageBubbleOutgoing: {
    backgroundColor: "#182536",
    borderWidth: 1,
    borderColor: "#2B3950",
    borderTopWidth: 1.5,
    borderTopColor: "rgba(255,180,120,0.6)",
    borderTopRightRadius: 18,
    borderBottomRightRadius: 10,
    shadowColor: colors.ink900,
    shadowOpacity: 0.1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  messageBubbleEngineering: {
    backgroundColor: "#FFF2E6",
    borderWidth: 1,
    borderColor: "#F0C9A4",
    borderLeftWidth: 3,
    borderLeftColor: "#F3B67A",
    borderTopLeftRadius: 18,
    borderBottomLeftRadius: 10,
    shadowColor: colors.ink900,
    shadowOpacity: 0.03,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 2,
  },
  messageBubbleReferenced: {
    borderColor: "#F6C190",
    borderWidth: 1.5,
  },
  messageAuthor: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  messageAuthorOutgoing: {
    color: colors.accentSoft,
  },
  messageHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  messageStatusBadge: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: radii.pill,
    borderWidth: 1,
  },
  messageStatusBadgeAccent: {
    backgroundColor: "#FFF1E4",
    borderColor: "#FFD6B2",
  },
  messageStatusBadgeSuccess: {
    backgroundColor: "#EEF9F3",
    borderColor: "#BCE8D0",
  },
  messageStatusBadgeText: {
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  messageStatusBadgeTextAccent: {
    color: colors.accent,
  },
  messageStatusBadgeTextSuccess: {
    color: colors.success,
  },
  messageText: {
    color: colors.textPrimary,
    fontSize: 15,
    lineHeight: 24,
  },
  messageTextOutgoing: {
    color: colors.white,
  },
  messageMeta: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  messageMetaOutgoing: {
    color: "rgba(255,255,255,0.74)",
    alignSelf: "flex-end",
  },
  messageReferenceCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E8D7C6",
    backgroundColor: "#FFF8F1",
    paddingHorizontal: spacing.sm,
    paddingVertical: 10,
  },
  messageReferenceCardOutgoing: {
    borderColor: "rgba(255,255,255,0.24)",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  messageReferenceIcon: {
    width: 24,
    height: 24,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFE9D4",
  },
  messageReferenceIconOutgoing: {
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  messageReferenceCopy: {
    flex: 1,
    gap: 2,
  },
  messageReferenceTitle: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  messageReferenceTitleOutgoing: {
    color: "rgba(255,255,255,0.86)",
  },
  messageReferenceText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  messageReferenceTextOutgoing: {
    color: "rgba(255,255,255,0.8)",
  },
  messageActionRow: {
    paddingTop: 2,
  },
  messageActionButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: "#EEC8A7",
    backgroundColor: "#FFF2E5",
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
  },
  messageActionText: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "700",
  },
  messageAttachments: {
    gap: spacing.xs,
  },
  messageAttachmentCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: "#FFF7EF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EEDCC9",
    padding: spacing.sm,
  },
  messageAttachmentCardDisabled: {
    opacity: 0.7,
  },
  messageAttachmentIconCircle: {
    width: 38,
    height: 38,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFE8D2",
  },
  messageAttachmentImagePreview: {
    width: 52,
    height: 52,
    borderRadius: radii.sm,
    backgroundColor: "#E8EDF2",
  },
  messageAttachmentBody: {
    flex: 1,
    gap: 2,
  },
  messageAttachmentTitle: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "600",
  },
  messageAttachmentCaption: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  messageAttachmentAction: {
    width: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  typingRow: {
    alignItems: "flex-start",
  },
  typingBubble: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: "#FFFBF7",
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#E8D8C9",
  },
  typingText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "600",
  },
  composerCard: {
    backgroundColor: "#FFFCF8",
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "#EAD9C8",
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.lg,
    gap: spacing.sm,
    shadowColor: colors.ink900,
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  composerCardKeyboardVisible: {
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
    gap: spacing.xs,
  },
  composerHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  composerHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  composerEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  composerTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  composerSubtitle: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  composerStatusBadge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  composerStatusBadgeAccent: {
    backgroundColor: "#FFF2E5",
    borderColor: "#EEC8A7",
  },
  composerStatusBadgeSuccess: {
    backgroundColor: "#EEF9F3",
    borderColor: "#BCE8D0",
  },
  composerStatusBadgeText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  composerStatusBadgeTextAccent: {
    color: colors.accent,
  },
  composerStatusBadgeTextSuccess: {
    color: colors.success,
  },
  composerHint: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    paddingHorizontal: 2,
  },
  composerToolsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    flexWrap: "wrap",
  },
  composerToolsLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  composerToolsText: {
    color: colors.textSecondary,
    fontSize: 12,
    flex: 1,
    textAlign: "left",
    minWidth: 180,
  },
  attachButton: {
    width: 42,
    height: 42,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  attachButtonDisabled: {
    opacity: 0.45,
  },
  attachmentDraftCard: {
    backgroundColor: "#FFFCF8",
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: "#E8D8C9",
    padding: spacing.md,
  },
  attachmentDraftHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  attachmentDraftIcon: {
    width: 36,
    height: 36,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFEEDF",
  },
  attachmentDraftPreview: {
    width: 52,
    height: 52,
    borderRadius: radii.sm,
    backgroundColor: "#E8EDF2",
  },
  attachmentDraftCopy: {
    flex: 1,
    gap: 2,
  },
  attachmentDraftTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  attachmentDraftDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  attachmentDraftRemove: {
    width: 30,
    height: 30,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  composerReferenceCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: "#E7D8C8",
    backgroundColor: "#FFF8F1",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  composerReferenceCopy: {
    flex: 1,
    gap: 2,
  },
  composerReferenceTitle: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  composerReferenceText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  composerReferenceRemove: {
    width: 28,
    height: 28,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  attachmentModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(9, 16, 25, 0.84)",
    padding: spacing.lg,
    justifyContent: "center",
  },
  activityModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(9,16,25,0.54)",
    padding: spacing.md,
    justifyContent: "flex-end",
  },
  activityModalCard: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: radii.lg,
    padding: spacing.lg,
    gap: spacing.md,
    maxHeight: "78%",
  },
  activityModalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  activityModalCopy: {
    flex: 1,
    gap: 2,
  },
  activityModalEyebrow: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  activityModalTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "800",
  },
  activityModalDescription: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  activityModalClose: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  activityModalLoading: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  activityModalLoadingText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  activityModalList: {
    gap: spacing.sm,
    paddingBottom: spacing.lg,
  },
  activityItem: {
    borderRadius: radii.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    padding: spacing.md,
    flexDirection: "row",
    gap: spacing.sm,
  },
  activityItemUnread: {
    borderColor: "#EFC9A8",
    backgroundColor: "#FFF8F1",
  },
  activityItemIcon: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    backgroundColor: "rgba(244,123,32,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  activityItemBody: {
    flex: 1,
    gap: 4,
  },
  activityItemTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  activityItemTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  activityItemTime: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
  },
  activityItemText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  activityItemHint: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "700",
  },
  activityEmptyState: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    paddingVertical: spacing.xxl,
  },
  activityEmptyTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  activityEmptyText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  sidePanelLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 18,
  },
  sidePanelModalRoot: {
    flex: 1,
  },
  sidePanelEdgeHitbox: {
    position: "absolute",
    top: PANEL_EDGE_GESTURE_TOP_OFFSET,
    bottom: 0,
    width: PANEL_EDGE_GESTURE_WIDTH,
    zIndex: 2,
  },
  sidePanelEdgeHitboxLeft: {
    left: 0,
  },
  sidePanelEdgeHitboxRight: {
    right: 0,
  },
  sidePanelScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(9,16,25,0.14)",
    zIndex: 3,
  },
  sidePanelScrimPressable: {
    flex: 1,
  },
  sidePanelDrawer: {
    position: "absolute",
    top: spacing.md,
    bottom: spacing.md,
    width: SIDE_PANEL_WIDTH,
    backgroundColor: "#FFFCF8",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#E9D9C8",
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    shadowColor: colors.ink900,
    shadowOpacity: 0.12,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 14 },
    elevation: 12,
    zIndex: 4,
  },
  sidePanelDrawerLeft: {
    left: spacing.md,
  },
  sidePanelDrawerRight: {
    right: spacing.md,
  },
  sidePanelHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  sidePanelCopy: {
    flex: 1,
    gap: 4,
  },
  sidePanelTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "800",
  },
  sidePanelDescription: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  sidePanelCloseButton: {
    width: 40,
    height: 40,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF7EE",
    borderWidth: 1,
    borderColor: "#EAD9C8",
  },
  sidePanelActionList: {
    gap: spacing.sm,
    paddingBottom: spacing.xl,
  },
  settingsDrawerContent: {
    gap: spacing.lg,
    paddingBottom: spacing.xl,
  },
  settingsSummaryCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#E9D9C8",
    backgroundColor: "#FFF8F0",
    padding: spacing.lg,
    gap: spacing.md,
    shadowColor: colors.ink900,
    shadowOpacity: 0.05,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 2,
  },
  settingsSummaryTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
  },
  settingsSummaryMark: {
    width: 54,
    height: 54,
    borderRadius: 18,
  },
  settingsSummaryCopy: {
    flex: 1,
    gap: 2,
  },
  settingsSummaryEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  settingsSummaryName: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "800",
  },
  settingsSummaryMeta: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  settingsSummaryChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  settingsOverviewGrid: {
    gap: spacing.sm,
  },
  settingsOverviewCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.md,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#E7DDD1",
    backgroundColor: "#FFFDFC",
    padding: spacing.md,
    shadowColor: colors.ink900,
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  settingsOverviewCardAccent: {
    backgroundColor: "#FFF8F0",
    borderColor: "#EBD7C2",
  },
  settingsOverviewCardSuccess: {
    backgroundColor: "#F6FCF8",
    borderColor: "#CFE7D7",
  },
  settingsOverviewCardDanger: {
    backgroundColor: "#FFF8F6",
    borderColor: "#F0D1CA",
  },
  settingsOverviewIcon: {
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E8DDD1",
    backgroundColor: "#F8F3ED",
  },
  settingsOverviewIconAccent: {
    backgroundColor: "#FFF1E3",
    borderColor: "#F3D8BC",
  },
  settingsOverviewIconSuccess: {
    backgroundColor: "#EEF8F1",
    borderColor: "#CCE3D2",
  },
  settingsOverviewIconDanger: {
    backgroundColor: "#FFF1F0",
    borderColor: "#F0CFC7",
  },
  settingsOverviewCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  settingsOverviewHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  settingsOverviewTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  settingsOverviewDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  settingsSearchShell: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E8D8C9",
    backgroundColor: "#FFF8F1",
  },
  settingsSearchInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 15,
    paddingVertical: 11,
  },
  settingsSearchClearButton: {
    width: 28,
    height: 28,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF1E4",
  },
  settingsFilterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  settingsFilterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: "#FFFDFC",
    borderWidth: 1,
    borderColor: "#E7DDD2",
  },
  settingsFilterChipActive: {
    backgroundColor: "#FFF1E4",
    borderColor: "#FFD6B2",
  },
  settingsFilterChipText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  settingsFilterChipTextActive: {
    color: colors.accent,
  },
  settingsFilterCount: {
    minWidth: 24,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  settingsFilterCountActive: {
    backgroundColor: colors.accent,
  },
  settingsFilterCountText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  settingsFilterCountTextActive: {
    color: colors.white,
  },
  settingsFilterSummary: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    paddingHorizontal: 4,
  },
  settingsSheetContent: {
    gap: spacing.md,
    paddingBottom: spacing.lg,
  },
  settingsFlowStack: {
    gap: spacing.md,
  },
  settingsInlineHero: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#EAD9C7",
    backgroundColor: "#FFF8F0",
    padding: spacing.md,
  },
  settingsInlineHeroMark: {
    width: 52,
    height: 52,
    borderRadius: 18,
  },
  settingsInlineHeroCopy: {
    flex: 1,
    gap: 4,
  },
  settingsInlineHeroTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  settingsInlineHeroText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  settingsInfoCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E8DDD1",
    backgroundColor: "#FFFDFC",
    padding: spacing.md,
    gap: 6,
  },
  settingsInfoTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  settingsInfoText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  settingsInfoSubtle: {
    color: colors.ink600,
    fontSize: 11,
    lineHeight: 16,
  },
  settingsInfoGrid: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  settingsInfoGridItem: {
    flex: 1,
  },
  settingsMiniList: {
    gap: spacing.sm,
  },
  settingsMiniListItem: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E8DDD1",
    backgroundColor: "#FFFDFC",
    padding: spacing.md,
    gap: 4,
  },
  settingsMiniListTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  settingsMiniListMeta: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  settingsHelpArticleHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  settingsHelpArticleCopy: {
    flex: 1,
    gap: 2,
  },
  settingsHelpArticleBody: {
    color: colors.textPrimary,
    fontSize: 12,
    lineHeight: 20,
    paddingTop: spacing.xs,
  },
  settingsSheetNotice: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#CAE7D5",
    backgroundColor: "#EFFAF3",
    padding: spacing.md,
  },
  settingsSheetNoticeText: {
    flex: 1,
    color: colors.success,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
  },
  settingsSheetFooter: {
    flexDirection: "row",
    gap: spacing.sm,
    paddingTop: spacing.xs,
  },
  settingsSheetGhostButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E7DDD2",
    backgroundColor: "#FFFDFC",
    alignItems: "center",
    justifyContent: "center",
  },
  settingsSheetGhostButtonText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  settingsSheetPrimaryButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 16,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsSheetPrimaryButtonDisabled: {
    opacity: 0.55,
  },
  settingsSheetPrimaryButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "800",
  },
  confirmSheetCard: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: radii.lg,
    padding: spacing.lg,
    gap: spacing.md,
    maxHeight: "68%",
  },
  confirmSheetIcon: {
    width: 42,
    height: 42,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF1F1",
    borderWidth: 1,
    borderColor: "#F1CCCC",
  },
  confirmSheetTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "800",
  },
  confirmSheetText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  confirmSheetHint: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  confirmSheetHintStrong: {
    color: colors.danger,
    fontWeight: "800",
  },
  confirmSheetDangerButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 16,
    backgroundColor: colors.danger,
    alignItems: "center",
    justifyContent: "center",
  },
  confirmSheetDangerButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "800",
  },
  settingsGroupLabel: {
    gap: 4,
    paddingHorizontal: 4,
  },
  settingsGroupEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  settingsGroupDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  settingsSection: {
    gap: spacing.sm,
  },
  settingsSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  settingsSectionIcon: {
    width: 36,
    height: 36,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF3E6",
    borderWidth: 1,
    borderColor: "#F3D6B7",
  },
  settingsSectionCopy: {
    flex: 1,
    gap: 2,
  },
  settingsSectionTitle: {
    color: colors.textPrimary,
    fontSize: 17,
    fontWeight: "800",
  },
  settingsSectionSubtitle: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  settingsCard: {
    backgroundColor: "#FFFDFC",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#E8DDD1",
    overflow: "hidden",
    shadowColor: colors.ink900,
    shadowOpacity: 0.035,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  settingsRow: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: "#F1E8DF",
  },
  settingsRowDanger: {
    backgroundColor: "#FFF9F8",
  },
  settingsBlockRow: {
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: "#F1E8DF",
  },
  settingsBlockHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  settingsRowIcon: {
    width: 34,
    height: 34,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF7EE",
    borderWidth: 1,
    borderColor: "#EEDCCB",
  },
  settingsRowIconDanger: {
    backgroundColor: "#FFF0F0",
    borderColor: "#F3C9C9",
  },
  settingsRowCopy: {
    flex: 1,
    gap: 3,
  },
  settingsRowTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  settingsRowTitleDanger: {
    color: colors.danger,
  },
  settingsRowDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  settingsRowMeta: {
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 4,
  },
  settingsRowValue: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
    maxWidth: 96,
  },
  settingsSegmentedControl: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  settingsSegmentPill: {
    minHeight: 36,
    paddingHorizontal: 14,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF7EE",
    borderWidth: 1,
    borderColor: "#EFDCC9",
  },
  settingsSegmentPillActive: {
    backgroundColor: colors.ink800,
    borderColor: colors.ink800,
  },
  settingsSegmentText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "capitalize",
  },
  settingsSegmentTextActive: {
    color: colors.textInverse,
  },
  settingsScaleValue: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "800",
  },
  settingsScaleTrack: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  settingsScaleStep: {
    flex: 1,
    height: 16,
    borderRadius: radii.pill,
    backgroundColor: "#EEE3D6",
    justifyContent: "center",
    alignItems: "center",
  },
  settingsScaleStepActive: {
    backgroundColor: "#FFD8B8",
  },
  settingsScaleDot: {
    width: 8,
    height: 8,
    borderRadius: radii.pill,
    backgroundColor: "#CEB8A1",
  },
  settingsScaleDotActive: {
    width: 10,
    height: 10,
    backgroundColor: colors.accent,
  },
  settingsScaleLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  settingsScaleLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "600",
  },
  settingsFieldBlock: {
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: "#F1E8DF",
  },
  settingsFieldBlockNoDivider: {
    gap: spacing.xs,
  },
  settingsFieldLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  settingsTextField: {
    minHeight: 48,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E8DDD1",
    backgroundColor: "#FFF8F1",
    color: colors.textPrimary,
    paddingHorizontal: spacing.md,
    fontSize: 15,
  },
  settingsTextArea: {
    minHeight: 124,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E8DDD1",
    backgroundColor: "#FFF8F1",
    color: colors.textPrimary,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    fontSize: 15,
    textAlignVertical: "top",
  },
  settingsStatusPill: {
    minHeight: 24,
    paddingHorizontal: 10,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F4ECE2",
    borderWidth: 1,
    borderColor: "#E5D6C6",
  },
  settingsStatusPillSuccess: {
    backgroundColor: "#E9F8EF",
    borderColor: "#C8E7D3",
  },
  settingsStatusPillDanger: {
    backgroundColor: "#FFF1F1",
    borderColor: "#F0C7C7",
  },
  settingsStatusPillAccent: {
    backgroundColor: "#FFF3E6",
    borderColor: "#F5D5B6",
  },
  settingsStatusPillText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
  },
  settingsStatusPillTextSuccess: {
    color: colors.success,
  },
  settingsStatusPillTextDanger: {
    color: colors.danger,
  },
  settingsStatusPillTextAccent: {
    color: colors.accent,
  },
  securityStack: {
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: "#F1E8DF",
  },
  securityIntroCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E9DCCF",
    backgroundColor: "#FFF8F1",
    padding: spacing.md,
    gap: 6,
  },
  securityIntroTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  securityIntroText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  securityRecoveryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
    paddingTop: spacing.xs,
  },
  securityRecoveryCode: {
    minWidth: 108,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E9DCCF",
    backgroundColor: "#FFFDF9",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  securityRecoveryCodeText: {
    color: colors.textPrimary,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.6,
  },
  securityProviderCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E9DCCF",
    backgroundColor: "#FFFCF8",
    padding: spacing.md,
    gap: spacing.sm,
  },
  securityProviderMain: {
    flexDirection: "row",
    gap: spacing.sm,
    alignItems: "center",
  },
  securityProviderIconShell: {
    width: 42,
    height: 42,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF6EE",
    borderWidth: 1,
    borderColor: "#E9DCCF",
  },
  securityProviderCopy: {
    flex: 1,
    gap: 4,
  },
  securityProviderHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  securityProviderTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  securityProviderMeta: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  securityProviderActionButton: {
    alignSelf: "flex-start",
    minHeight: 34,
    paddingHorizontal: 14,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.ink800,
  },
  securityProviderActionButtonDanger: {
    backgroundColor: "#FFF3F2",
    borderWidth: 1,
    borderColor: "#F2D3CF",
  },
  securityProviderActionText: {
    color: colors.textInverse,
    fontSize: 12,
    fontWeight: "800",
  },
  securityProviderActionTextDanger: {
    color: colors.danger,
  },
  securitySessionCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E9DCCF",
    backgroundColor: "#FFFCF8",
    padding: spacing.md,
    gap: spacing.sm,
  },
  securitySessionTop: {
    gap: spacing.xs,
  },
  securitySessionCopy: {
    gap: 4,
  },
  securitySessionHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  securitySessionTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  securitySessionMeta: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  securitySessionActionButton: {
    alignSelf: "flex-start",
    minHeight: 34,
    paddingHorizontal: 14,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF3E6",
    borderWidth: 1,
    borderColor: "#E9DCCF",
  },
  securitySessionActionButtonDisabled: {
    backgroundColor: "#F4ECE2",
  },
  securitySessionActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  securitySessionReviewButton: {
    backgroundColor: "#FFF6EE",
    borderColor: "#E9DCCF",
  },
  securitySessionReviewButtonDanger: {
    backgroundColor: "#FFF1F1",
    borderColor: "#F0C7C7",
  },
  securitySessionActionText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "800",
  },
  securitySessionReviewButtonText: {
    color: colors.accent,
  },
  securitySessionReviewButtonTextDanger: {
    color: colors.danger,
  },
  securityEventCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E9DCCF",
    backgroundColor: "#FFFCF8",
    padding: spacing.md,
    gap: 6,
  },
  securityEventTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  securityEventTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  securityEventMeta: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  securityEventStatus: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  securityFootnote: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  historyModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(9,16,25,0.14)",
    padding: spacing.md,
    justifyContent: "flex-end",
  },
  historyModalCard: {
    backgroundColor: "#FFFDF9",
    borderRadius: 30,
    padding: spacing.lg,
    gap: spacing.md,
    maxHeight: "82%",
    shadowColor: colors.ink900,
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  historyModalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  historyBrandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginBottom: 2,
  },
  historyBrandIcon: {
    width: 28,
    height: 28,
    borderRadius: 10,
  },
  historyBrandEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  historyModalCopy: {
    flex: 1,
    gap: 4,
  },
  historyModalTitle: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: "800",
  },
  historyModalSubtitle: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  historyModalClose: {
    width: 40,
    height: 40,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF8F1",
    borderWidth: 1,
    borderColor: "#E8D8C9",
  },
  historySearchShell: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E8D8C9",
    backgroundColor: "#FFF8F1",
  },
  historySearchInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 16,
    paddingVertical: 12,
  },
  historySummaryCard: {
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#E8D8C9",
    borderTopColor: "#F0B98B",
    borderTopWidth: 1.5,
    backgroundColor: "#FFF8F1",
  },
  historySummaryMetrics: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  historySummaryMetric: {
    flex: 1,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    borderRadius: 18,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#EADFD4",
    gap: 2,
  },
  historySummaryMetricValue: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "800",
  },
  historySummaryMetricLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  historySummaryText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  historyFilterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  historyFilterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  historyFilterChipActive: {
    backgroundColor: "#FFF1E4",
    borderColor: "#FFD6B2",
  },
  historyFilterChipText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  historyFilterChipTextActive: {
    color: colors.accent,
  },
  historyFilterCount: {
    minWidth: 24,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  historyFilterCountActive: {
    backgroundColor: colors.accent,
  },
  historyFilterCountText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  historyFilterCountTextActive: {
    color: colors.white,
  },
  historySections: {
    gap: spacing.lg,
    paddingBottom: spacing.lg,
  },
  historySection: {
    gap: spacing.sm,
  },
  historySectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  historySectionTitle: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  historySectionCountBadge: {
    minWidth: 26,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF1E4",
    borderWidth: 1,
    borderColor: "#FFD6B2",
  },
  historySectionCountText: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
  },
  historySectionItems: {
    gap: spacing.sm,
  },
  historyItemShell: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: spacing.xs,
  },
  historyItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#E7DDD2",
    backgroundColor: "#FFFDFB",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    shadowColor: colors.ink900,
    shadowOpacity: 0.035,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 2,
  },
  historyItemPrimary: {
    flex: 1,
  },
  historyItemActive: {
    backgroundColor: colors.ink800,
    borderColor: colors.ink800,
    shadowOpacity: 0.08,
    elevation: 4,
  },
  historyItemActions: {
    justifyContent: "center",
    gap: spacing.xs,
  },
  historyItemActionButton: {
    width: 42,
    height: 42,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF4E8",
    borderWidth: 1,
    borderColor: "#E7DDD2",
    shadowColor: colors.ink900,
    shadowOpacity: 0.025,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  historyItemActionButtonPinned: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  historyItemActionButtonDanger: {
    backgroundColor: "#FFF8F4",
    borderColor: "#EBD5CA",
  },
  historyItemIcon: {
    width: 42,
    height: 42,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF8F1",
    borderWidth: 1,
    borderColor: "#E7DDD2",
  },
  historyItemIconActive: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.18)",
  },
  historyItemBrandIcon: {
    width: 26,
    height: 26,
    borderRadius: 8,
  },
  historyItemCopy: {
    flex: 1,
    gap: 4,
  },
  historyItemMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    flexWrap: "wrap",
  },
  historyItemInfoTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: radii.pill,
    backgroundColor: "#FFF7EF",
    borderWidth: 1,
    borderColor: "#E7DDD2",
  },
  historyItemInfoTagEditable: {
    backgroundColor: "#EEF9F3",
    borderColor: "#BCE8D0",
  },
  historyItemInfoTagActive: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.14)",
  },
  historyItemInfoTagText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
  },
  historyItemInfoTagTextEditable: {
    color: colors.success,
  },
  historyItemInfoTagTextActive: {
    color: colors.white,
  },
  historyItemHeading: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  historyItemTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  historyItemTitleActive: {
    color: colors.white,
  },
  historyItemTime: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  historyItemTimeActive: {
    color: "rgba(255,255,255,0.72)",
  },
  historyItemPreview: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  historyItemPreviewActive: {
    color: "rgba(255,255,255,0.84)",
  },
  historyItemStatus: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  historyItemStatusAccent: {
    backgroundColor: "#FFF1E4",
    borderColor: "#FFD6B2",
  },
  historyItemStatusSuccess: {
    backgroundColor: "#EEF9F3",
    borderColor: "#BCE8D0",
  },
  historyItemStatusDanger: {
    backgroundColor: "#FDEEEE",
    borderColor: "#F6CACA",
  },
  historyItemStatusActive: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.18)",
  },
  historyItemStatusText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  historyItemStatusTextAccent: {
    color: colors.accent,
  },
  historyItemStatusTextSuccess: {
    color: colors.success,
  },
  historyItemStatusTextDanger: {
    color: colors.danger,
  },
  historyItemStatusTextActive: {
    color: colors.white,
  },
  historyItemPinnedTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: radii.pill,
    backgroundColor: "#FFF8F1",
    borderWidth: 1,
    borderColor: "#E9D9C8",
  },
  historyItemPinnedTagActive: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.18)",
  },
  historyItemPinnedTagText: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
  },
  historyItemPinnedTagTextActive: {
    color: colors.white,
  },
  historyEmptyState: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    paddingVertical: spacing.xxl,
  },
  historyEmptyBrand: {
    width: 56,
    height: 56,
    borderRadius: 18,
  },
  historyEmptyTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  historyEmptyText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  attachmentModalCard: {
    backgroundColor: "#08111C",
    borderRadius: radii.lg,
    padding: spacing.md,
    gap: spacing.md,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  attachmentModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  attachmentModalTitle: {
    flex: 1,
    color: colors.white,
    fontSize: 14,
    fontWeight: "700",
  },
  attachmentModalClose: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  attachmentModalImage: {
    width: "100%",
    minHeight: 280,
    maxHeight: 520,
    borderRadius: radii.md,
    backgroundColor: "#03070D",
  },
  composerRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: "#E9DACA",
    backgroundColor: "#FFFDF9",
    borderRadius: 24,
    paddingLeft: spacing.md,
    paddingRight: 6,
    paddingVertical: 6,
  },
  attachInsideButton: {
    width: 40,
    height: 40,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF1E2",
    borderWidth: 1,
    borderColor: "#EFCBA8",
    marginBottom: 2,
  },
  composerInput: {
    flex: 1,
    minHeight: 48,
    maxHeight: 160,
    backgroundColor: "transparent",
    borderRadius: 0,
    borderWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 12,
    color: colors.textPrimary,
    fontSize: 15,
  },
  composerInputDisabled: {
    color: colors.textSecondary,
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: radii.pill,
    backgroundColor: "#F47B20",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.accent,
    shadowOpacity: 0.24,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 9 },
    elevation: 4,
  },
  sendButtonDisabled: {
    opacity: 0.55,
  },
  metricsRow: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  metricCard: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: radii.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    gap: 6,
  },
  metricValue: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: "800",
  },
  metricLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  actionList: {
    gap: spacing.sm,
  },
  actionItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    backgroundColor: colors.white,
    borderRadius: radii.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  actionText: {
    color: colors.textPrimary,
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
});
