import type { ComponentProps } from "react";

import { TARIEL_APP_MARK } from "../InspectorMobileApp.constants";
import { InspectorAuthenticatedLayout } from "../InspectorAuthenticatedLayout";

type BuildAuthenticatedLayoutPropsInput = Record<string, any>;

export function buildAuthenticatedLayoutProps(
  input: BuildAuthenticatedLayoutPropsInput,
): ComponentProps<typeof InspectorAuthenticatedLayout> {
  const {
    accentColor,
    animacoesAtivas,
    anexoAbrindoChave,
    anexoMesaRascunho,
    anexoRascunho,
    appGradientColors,
    abrirReferenciaNoChat,
    buscaHistorico,
    carregandoConversa,
    carregandoMesa,
    chipsContextoThread,
    composerKeyboardBottomOffset,
    configuracoesAberta,
    conversaAtiva,
    conversaVazia,
    conversasFixadasTotal,
    conversasOcultasTotal,
    conversasVisiveisTotal,
    definirReferenciaMesaAtiva,
    drawerOverlayOpacity,
    dynamicComposerInputStyle,
    dynamicMessageBubbleStyle,
    dynamicMessageTextStyle,
    enviandoMensagem,
    enviandoMesa,
    erroConversa,
    erroLaudos,
    erroMesa,
    fecharHistorico,
    fecharPaineisLaterais,
    filaOfflineOrdenada,
    filtroHistorico,
    filtrosHistoricoComContagem,
    handleAbrirAnexo,
    handleAbrirConfiguracoes,
    handleAbrirHistorico,
    handleAbrirSeletorAnexo,
    handleAlternarFixadoHistorico,
    handleEnviarMensagem,
    handleEnviarMensagemMesa,
    handleExcluirConversaHistorico,
    handleReabrir,
    handleSelecionarHistorico,
    headerSafeTopInset,
    historicoAberto,
    historicoAgrupadoFinal,
    historicoDrawerX,
    historicoVazioTexto,
    historicoVazioTitulo,
    historyDrawerPanResponder,
    historyEdgePanResponder,
    introVisivel,
    keyboardAvoidingBehavior,
    keyboardVisible,
    laudoContextDescription,
    laudoContextTitle,
    laudoSelecionadoId,
    limparReferenciaMesaAtiva,
    mesaDisponivel,
    mesaTemMensagens,
    mensagem,
    mensagemChatDestacadaId,
    mensagemMesa,
    mensagemMesaReferenciaAtiva,
    mensagensMesa,
    mensagensVisiveis,
    mostrarContextoThread,
    nomeUsuarioExibicao,
    notificacoesMesaLaudoAtual,
    notificacoesNaoLidas,
    obterResumoReferenciaMensagem,
    placeholderComposer,
    placeholderMesa,
    podeAbrirAnexosChat,
    podeAbrirAnexosMesa,
    podeAcionarComposer,
    podeEnviarComposer,
    podeEnviarMesa,
    podeUsarComposerMesa,
    registrarLayoutMensagemChat,
    resumoHistoricoDrawer,
    scrollRef,
    sessionAccessToken,
    sessionModalsStackProps,
    setAbaAtiva,
    setAnexoMesaRascunho,
    setAnexoRascunho,
    setBuscaHistorico,
    setFiltroHistorico,
    setIntroVisivel,
    setMensagem,
    setMensagemMesa,
    settingsDrawerPanelProps,
    settingsEdgePanResponder,
    threadInsights,
    threadKeyboardPaddingBottom,
    threadSpotlight,
    vendoMesa,
    chaveAnexo,
    formatarHorarioAtividade,
    formatarTipoTemplateLaudo,
  } = input;

  return {
    accentColor,
    animacoesAtivas,
    appGradientColors,
    chatKeyboardVerticalOffset: input.chatKeyboardVerticalOffset,
    drawerOverlayOpacity,
    erroConversa,
    erroLaudos,
    historyDrawerPanelProps: {
      brandMarkSource: TARIEL_APP_MARK,
      buscaHistorico,
      conversasFixadasTotal,
      conversasOcultasTotal,
      conversasVisiveisTotal,
      filtroHistorico,
      filtrosHistoricoComContagem,
      formatarHorarioAtividade,
      formatarTipoTemplateLaudo,
      historicoAgrupadoFinal,
      historicoDrawerX,
      historicoVazioTexto,
      historicoVazioTitulo,
      historyDrawerPanResponder,
      laudoSelecionadoId,
      onAlternarFixadoHistorico: (item: any) => handleAlternarFixadoHistorico(item),
      onBuscaHistoricoChange: setBuscaHistorico,
      onCloseHistory: () => fecharHistorico({ limparBusca: true }),
      onExcluirConversaHistorico: (item: any) => handleExcluirConversaHistorico(item),
      onFiltroHistoricoChange: (key: any) => setFiltroHistorico(key),
      onSelecionarHistorico: (item: any) => {
        void handleSelecionarHistorico(item);
      },
      resumoHistoricoDrawer,
    },
    historyEdgePanHandlers: historyEdgePanResponder.panHandlers,
    historyOpen: historicoAberto,
    introVisivel,
    keyboardAvoidingBehavior,
    keyboardVisible,
    mesaTemMensagens,
    onClosePanels: fecharPaineisLaterais,
    onIntroDone: () => setIntroVisivel(false),
    sessionModalsStackProps,
    settingsDrawerPanelProps,
    settingsDrawerVisible: configuracoesAberta,
    settingsEdgePanHandlers: settingsEdgePanResponder.panHandlers,
    settingsOpen: configuracoesAberta,
    threadComposerPanelProps: {
      accentColor,
      anexoMesaRascunho,
      anexoRascunho,
      canReopen: Boolean(conversaAtiva?.permiteReabrir),
      composerKeyboardBottomOffset,
      dynamicComposerInputStyle,
      enviandoMensagem,
      enviandoMesa,
      erroMesa,
      keyboardVisible,
      mensagem,
      mensagemMesa,
      mensagemMesaReferenciaAtiva,
      onAbrirSeletorAnexo: handleAbrirSeletorAnexo,
      onClearAnexoMesaRascunho: () => setAnexoMesaRascunho(null),
      onClearAnexoRascunho: () => setAnexoRascunho(null),
      onEnviarMensagem: () => {
        void handleEnviarMensagem();
      },
      onEnviarMensagemMesa: () => {
        void handleEnviarMensagemMesa();
      },
      onLimparReferenciaMesaAtiva: limparReferenciaMesaAtiva,
      onReopen: handleReabrir,
      onSetMensagem: setMensagem,
      onSetMensagemMesa: setMensagemMesa,
      placeholderComposer,
      placeholderMesa,
      podeAbrirAnexosChat,
      podeAbrirAnexosMesa,
      podeAcionarComposer,
      podeEnviarComposer,
      podeEnviarMesa,
      podeUsarComposerMesa,
      vendoMesa,
    },
    threadContextCardProps: {
      chips: chipsContextoThread,
      description: laudoContextDescription,
      eyebrow: vendoMesa ? "mesa avaliadora" : "chat do inspetor",
      insights: threadInsights,
      spotlight: threadSpotlight,
      title: laudoContextTitle,
    },
    threadContextVisible: mostrarContextoThread && vendoMesa,
    threadConversationPaneProps: {
      accentColor,
      anexoAbrindoChave,
      brandMarkSource: TARIEL_APP_MARK,
      carregandoConversa: carregandoConversa && !conversaAtiva,
      carregandoMesa,
      conversaPermiteEdicao: Boolean(conversaAtiva?.permiteEdicao),
      conversaVazia,
      dynamicMessageBubbleStyle,
      dynamicMessageTextStyle,
      enviandoMensagem,
      keyboardVisible,
      mesaDisponivel,
      mensagemChatDestacadaId,
      mensagensMesa,
      mensagensVisiveis,
      nomeUsuarioExibicao,
      obterResumoReferenciaMensagem,
      onAbrirAnexo: handleAbrirAnexo,
      onAbrirReferenciaNoChat: (id: number) => {
        void abrirReferenciaNoChat(id);
      },
      onDefinirReferenciaMesaAtiva: definirReferenciaMesaAtiva,
      onRegistrarLayoutMensagemChat: registrarLayoutMensagemChat,
      scrollRef,
      sessionAccessToken,
      threadKeyboardPaddingBottom,
      toAttachmentKey: chaveAnexo,
      vendoMesa,
    },
    threadHeaderControlsProps: {
      filaOfflineTotal: filaOfflineOrdenada.length,
      headerSafeTopInset,
      notificacoesMesaLaudoAtual,
      notificacoesNaoLidas,
      onOpenChatTab: () => setAbaAtiva("chat"),
      onOpenHistory: handleAbrirHistorico,
      onOpenMesaTab: () => setAbaAtiva("mesa"),
      onOpenSettings: handleAbrirConfiguracoes,
      vendoMesa,
    },
    vendoMesa,
  };
}
